import assert from 'node:assert/strict';
import fs from 'node:fs';
import {GROUPS,PARENTS,CHILDREN,observationCategories,matchesCategory,matchesChip,hasXpu} from '../lib/hierarchy.js';
import {categoryMonthRows,combinedAmountRows,eventKey} from '../lib/monthly.js';
import {panelMatrix,panelCell,periods} from '../lib/panel.js';
assert.equal(GROUPS.length,5);assert.equal(Object.keys(CHILDREN).length,14);
assert.equal(new Set(GROUPS.flatMap(g=>g.children)).size,14);
assert(matchesChip({tags:['hygon_dcu']},'hyg_dcu'));assert(matchesChip({tags:['kunpeng_cpu']},'kunpeng'));
assert.deepEqual(observationCategories({categories:[],tags:['hyg_or_kunpeng']}),['hygon','kunpeng_route']);
assert(!observationCategories({title:'海光CPU与鲲鹏服务器',categories:[]}).includes('domestic_gpu'));
assert(hasXpu('AI数据中心DPU加速'));assert(hasXpu('机架级XPU部署'));
assert(!hasXpu('昇腾开发者高校训练营'));assert(!hasXpu('边缘端NPU推理'));assert(!hasXpu('普通CPU GPU服务器'));
const e={id:'a',event_key:'event1',project_id:'p1',published_date:'2026-01-01',stage:'tender',categories:['aidc','liquid_cooling'],tags:[],amount_kind:'budget',amount_cny:100000};
const rows=[e,{...e,id:'b',event_key:'event2',published_date:'2026-02-01',stage:'contract',amount_kind:'contract',amount_cny:80000},{...e,id:'lot2',lot:'2',amount_cny:20000}];
const matrix=categoryMonthRows(rows,[],[],[],undefined,combinedAmountRows(rows),PARENTS);
assert.equal(matrix.find(r=>r.category==='facilities'&&r.month==='2026-01').events,1,'Two lots of one event count once');
assert.equal(matrix.find(r=>r.category==='facilities'&&r.month==='2026-01').total_amount,2);
assert.equal(matrix.find(r=>r.category==='facilities'&&r.month==='2026-02').total_amount,8,'Latest amount counted once despite two child categories');
const chipRows=[{...e,categories:[],tags:['hyg_or_kunpeng']}];
assert.equal(categoryMonthRows(chipRows,[],[],[],undefined,combinedAmountRows(chipRows),PARENTS).find(r=>r.category==='processors'&&r.month==='2026-01').total_amount,10);
assert.equal(combinedAmountRows([...rows,{...e,id:'cancel',published_date:'2026-03-01',stage:'cancel'}]).length,1,'Cancellation suppresses all stages of same lot before grouping');
const source={id:'a',coverage:[{month:'2026-01',status:'complete'}]},p=periods()[0],docs=[{id:'1',source_id:'a',date:'2026-01-01',month:'2026-01',categories:['aidc','liquid_cooling'],tags:[]},{id:'2',source_id:'a',date:'2026-01-01',month:'2026-01',categories:[],tags:[]}];
const cell=panelCell({documents:docs},source,'facilities','attention',p);assert.equal(cell.n,1);assert.equal(cell.N,2);assert.equal(cell.value,500);
assert.equal(panelCell({documents:docs},source,'facilities','attention',p,'kunpeng').N,2);
assert.equal(panelCell({documents:docs},source,'processors','application',p).status,'行为复核未完成');
const procurement={...source,denominators:{aidc:'适用建设标包',liquid_cooling:'适用冷却标包',modular_dc:'适用模块化标包'}};
const demand={documents:[{...docs[0],eligible:true,eligible_categories:['aidc','liquid_cooling'],required_categories:['aidc'],unknown_categories:['liquid_cooling']}]};
const pc=panelCell(demand,procurement,'facilities','demand',p);assert.deepEqual([pc.n,pc.N,pc.u],[1,1,0]);
assert.equal(panelCell(demand,procurement,'processors','demand',p).status,'适用分母未建立');
const read=name=>JSON.parse(fs.readFileSync(new URL('../'+name,import.meta.url)));
const data=read('public/market-panel.json'),all=data.sources.find(s=>s.id==='media_all');
for(const level of [PARENTS,CHILDREN])for(const row of panelMatrix(data,all,'attention','month','all',level))for(const point of row.points){
 assert.equal(point.N,data.documents.filter(d=>all.document_source_ids.includes(d.source_id)&&d.month===point.id&&!d.superseded).length);
 assert.equal(new Set(point.ids).size,point.n);
}
const study=read('data/research-2026.json'),research=[...study.events,...study.leads];
for(const id of Object.keys(PARENTS))assert.equal(new Set(research.filter(r=>matchesCategory(r,id)).map(eventKey)).size,new Set(GROUPS.find(g=>g.id===id).children.flatMap(c=>research.filter(r=>matchesCategory(r,c)).map(eventKey))).size);
assert.equal(data.documents.filter(d=>all.document_source_ids.includes(d.source_id)&&!d.superseded&&d.date>=data.window.start&&d.date<=data.window.end).length,data.latest_refresh?.unique_media_news??read('data/rolling-update.json').unique_media_news);
assert.deepEqual(read('public/sample-sources.json').taxonomy,data.taxonomy);
console.log('PASS: 5 parents/14 children, aliases, parent unions, latest amounts, cancellation, all-news denominators, demand unknowns and replay metadata.');
