import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const {dateWindow,monthsInWindow,partialMonth}=await import('../lib/model.js');
const {inObservationPeriod,monthlySeries,categoryMonthRows,amountRows}=await import('../lib/monthly.js');
const {periods,panelMatrix}=await import('../lib/panel.js');
assert.equal(monthsInWindow().length,9);
assert.equal(periods('quarter').at(-1).label,'Q3*');
assert.throws(()=>dateWindow({start:'2026-10-01',end:'2026-09-30'}));
assert.throws(()=>dateWindow({start:'2026-02-30',end:'2026-10-01'}));
const w={start:'2026-01-01',end:'2026-10-11'};
assert.equal(monthsInWindow(w).length,10);
assert(!partialMonth('2026-09',w));assert(partialMonth('2026-10',w));
assert(!partialMonth('2028-02',{start:'2028-02-01',end:'2028-02-29'}));
assert.deepEqual(periods('quarter',{start:'2026-11-01',end:'2027-02-10'}).map(p=>[p.id,p.partial]),[['2026-Q4',true],['2027-Q1',true]]);
const e={id:'date-check',project_id:'date-check',published_date:'2026-10-11',event_date:'2026-10-10',categories:['liquid_cooling'],tags:[],stage:'award',source_type:'buyer',customer:'test',verified_fulltext:true,evidence_status:'primary',amount_kind:'award',amount_cny:10000};
assert(!inObservationPeriod(e));assert(inObservationPeriod(e,w));
assert(!inObservationPeriod({...e,published_date:'2026-10-12'},w));
assert(!inObservationPeriod({...e,event_date:'2026-10-12'},w));
assert.equal(monthlySeries([e],'award',amountRows([e]),w).at(-1).amount,1);
assert.equal(categoryMonthRows([e],[],amountRows([e]),[],w).find(r=>r.category==='liquid_cooling'&&r.month==='2026-10').events,1);
const source={id:'news',kind:'news',coverage:monthsInWindow(w).map(month=>({month,status:'complete'}))},doc={id:'n',source_id:'news',date:'2026-10-10',month:'2026-10',categories:['liquid_cooling'],tags:[]};
const matrix=panelMatrix({window:w,documents:[doc,{...doc,id:'outside',date:'2026-10-12'}]},source,'attention');
const point=matrix.find(r=>r.id==='liquid_cooling').points.at(-1);
assert.equal(point.N,1);assert.equal(point.value,1000);assert(point.partial);
const baseline=JSON.parse(readFileSync(new URL('../data/research-2026.json',import.meta.url),'utf8'));
assert.deepEqual(dateWindow(baseline),{start:baseline.period_start,end:baseline.period_end});
console.log('PASS: snapshot defaults, October rollover, cross-year quarters, leap year, date boundaries, amount scale and panel denominators.');
