import assert from 'node:assert/strict';
import {parseImport,pendingRecord,canonicalUrl,importKey,ambiguousImport} from '../lib/imports.js';
import {robotsAllows,extractLinks,collectPage,publicationDate} from '../lib/collect.js';
import {workspaceResearch} from '../lib/unified-records.js';
import {combinedAmountRows,inObservationPeriod,categoryMonthRows} from '../lib/monthly.js';
import {sourcePanel,CATEGORIES} from '../data/sources.js';
assert.equal(new Set(sourcePanel.map(s=>s.category)).size,9);assert.equal(Object.keys(CATEGORIES).length,9);assert.equal(new Set(sourcePanel.map(s=>s.id)).size,sourcePanel.length);
const rows=parseImport('\uFEFF标题,链接,发布日期,正文\r\n"公告,液冷",https://www.h3c.com/cn/test,2026-09-01,"第一行\n第二行"','test.csv');
assert.equal(rows[0].title,'公告,液冷');assert.equal(rows[0].excerpt,'第一行\n第二行');
assert.throws(()=>parseImport('title,url\n"unclosed','test.csv'));
assert.throws(()=>parseImport('[{"title":"x","url":"javascript:alert(1)"}]','test.json'));
assert.throws(()=>parseImport(JSON.stringify(Array(51).fill(rows[0])),'test.json'));
assert.throws(()=>parseImport(JSON.stringify([{...rows[0],published_date:'2026-02-30'}]),'test.json'));
const pending=await pendingRecord({...rows[0],review_status:'accepted',verified_fulltext:true},'liquid_cooling','h3c');
assert.equal(pending.review_status,'pending');assert.equal(pending.value_cny,null);assert.equal(pending.verified_fulltext,false);assert.equal(pending.source_excerpt,rows[0].excerpt);
const cninfo=await pendingRecord({...rows[0],url:'https://static.cninfo.com.cn/report.pdf'},'token_factory','h3c');assert.equal(cninfo.source_id,'cninfo');assert.notEqual(cninfo.publisher,'新华三');assert.equal(cninfo.discovery_source_id,'h3c');
assert.equal((await pendingRecord({...rows[0],url:rows[0].url+'?utm_campaign=a#abc'},'liquid_cooling','h3c')).id,pending.id);
assert.equal(canonicalUrl('https://mp.weixin.qq.com/s?__biz=abc&mid=123#wechat'),'https://mp.weixin.qq.com/s?__biz=abc&mid=123');
const structured=parseImport('标题,链接,发布日期,项目编号,标包,金额,金额单位,金额类型,阶段,技术分类,芯片路线\n结构化采购,https://www.h3c.com/cn/structured,2026-09-10,P2026,包1,35,万元,预算,采购,液冷;算力场,海光 CPU','structured.csv')[0];
const structuredRecord=await pendingRecord(structured,'liquid_cooling','h3c'),researchRow=workspaceResearch(structuredRecord);
assert.equal(researchRow.amount_cny,350000);assert.equal(researchRow.stage,'tender');assert.equal(researchRow.project_id,'P2026');assert.equal(researchRow.lot,'包1');assert.equal(structuredRecord.review_status,'pending');assert(inObservationPeriod(researchRow));assert.equal(combinedAmountRows([researchRow])[0]._amount_min,350000);
assert.deepEqual(structuredRecord.techs,['liquid_cooling','compute_field']);assert.deepEqual(structuredRecord.tags,['hyg_cpu']);
assert.notEqual(importKey(structured),importKey({...structured,lot:'包2'}));assert.notEqual(structuredRecord.id,(await pendingRecord({...structured,lot:'包2'},'liquid_cooling','h3c')).id);
const otherProject={...structured,project_id:'P2026-OTHER'};
assert.notEqual(importKey(structured),importKey(otherProject));assert.notEqual(structuredRecord.id,(await pendingRecord(otherProject,'liquid_cooling','h3c')).id);
assert.equal(importKey(pending),importKey(rows[0]));
assert.equal(importKey({...rows[0],id:'old-record',project_id:'old-record'}),importKey(rows[0]));
assert.equal(importKey({...rows[0],project_id:pending.id}),importKey(rows[0]));
assert.equal((await pendingRecord({...rows[0],id:'old-record',project_id:'old-record'},'liquid_cooling','h3c')).id,pending.id);
assert.equal(ambiguousImport(structured,{...structured,project_id:''}),true);
assert.equal(ambiguousImport(structured,{...structured,project_id:'',lot:'包2'}),false);
assert.equal(ambiguousImport(structured,otherProject),false);
// The actual preview -> API parse -> workspace -> monthly path retains explicit focus classification and units.
const focusPreview=parseImport(JSON.stringify([{...structured,categories:[],tags:['hyg_cpu','kunpeng']}]),'focus.json')[0];
const focusRecord=workspaceResearch(await pendingRecord(focusPreview,'liquid_cooling','hygon'));
assert.deepEqual(focusRecord.categories,[]);assert.equal(focusRecord.amount_cny,350000);
const focusGrid=categoryMonthRows([focusRecord],[],[],[],undefined,combinedAmountRows([focusRecord])).filter(r=>r.total_amount_count);
assert.deepEqual(focusGrid.map(r=>[r.category,r.month,r.total_amount]),[['focus','2026-09',35]]);
assert.deepEqual(parseImport('标题,链接,技术分类,芯片路线\nCPU采购,https://www.h3c.com/cn/cpu,常规芯片采购补充,海光 CPU','focus.csv')[0].categories,[]);
assert.deepEqual((await pendingRecord(rows[0],'liquid_cooling','h3c')).techs,['liquid_cooling']);
assert.throws(()=>parseImport(JSON.stringify([{...rows[0],categories:[]}]),'bad.json'),/空技术分类/);
assert.throws(()=>parseImport(JSON.stringify([{...rows[0],categories:[],tags:['hyg_dcu']}]),'bad.json'),/空技术分类/);
assert.throws(()=>parseImport(JSON.stringify([{...rows[0],amount_cny:10}]),'bad.json'));
assert.throws(()=>parseImport(JSON.stringify([{...structured,amount_cny:true}]),'bad.json'));
assert.throws(()=>parseImport(JSON.stringify([{...structured,amount_unit:'美元'}]),'bad.json'));
assert.equal(publicationDate('<meta content="2026-09-12T12:00:00+08:00" property="article:published_time">'),'2026-09-12');
assert.equal(publicationDate('<p>发布日期：2026年9月3日</p>'),'2026-09-03');
assert.equal(publicationDate('<meta name="publishdate" content="2026-02-30">'),'');
assert.equal(publicationDate('<meta name="publishdate" content="2026-09-01"><meta itemprop="datePublished" content="2026-09-02">'),'');
assert.equal(publicationDate('<p>项目计划2026-09-01上线</p>'),'');
assert.equal(robotsAllows('User-agent: BadBot\nDisallow: /\nUser-agent: *\nDisallow: /private\nAllow: /private/public','/open'),true);
assert.equal(robotsAllows('User-agent: *\nDisallow: /private\nAllow: /private/public','/private/x'),false);
assert.equal(robotsAllows('User-agent: *\nDisallow: /private\nAllow: /private/public','/private/public'),true);
const links=extractLinks('<a href="/cn/a?x=1&amp;y=2">液冷服务器公告</a><a href="javascript:evil()">液冷危险链接</a><a href="https://other.example/post">液冷外部报道</a><a href="/cn/a?x=1&amp;y=2">液冷重复</a>','https://www.h3c.com/','液冷');
assert.equal(links.length,2);assert.equal(links[0].collectable,true);assert.equal(links[1].collectable,false);
const original=globalThis.fetch;
try{globalThis.fetch=async url=>url.endsWith('/robots.txt')?new Response('',{status:404}):new Response('%PDF-1.7 mock',{headers:{'content-type':'application/pdf'}});assert.equal((await collectPage('https://static.cninfo.com.cn/test.pdf')).status,'pdf');
 globalThis.fetch=async url=>url.endsWith('/robots.txt')?new Response('',{status:404}):new Response('<title>安全验证</title><p>请输入验证码</p>',{headers:{'content-type':'text/html'}});await assert.rejects(()=>collectPage('https://mp.weixin.qq.com/s/test'),/访问验证/);
}finally{globalThis.fetch=original;}
console.log('PASS: nine categories, CSV/JSON validation, pending-only imports, stable deduplication, robots groups, safe discovery, PDF and captcha classification');
