'use client';
import {useState} from 'react';
import {TECHS,safeUrl,dateWindow,monthsInWindow,monthLabel} from '@/lib/model';
import {PARENTS,CHILDREN,CLASS_LABELS,parentOf,TAXONOMY_NOTE,XPU_NOTE} from '@/lib/hierarchy';
import {panelColors} from '@/lib/panel';
import {categoryMonthRows,categoryMonthlyCsv} from '@/lib/monthly';
const metrics={total_amount:'合并披露金额',events:'收录独立事件'};
const fmt=n=>n==null?'—':n.toLocaleString('zh-CN',{maximumFractionDigits:2});
export default function CategoryTrends({window,rows,leads,eligible,reported,combined,category,month,onSelect,notes=[],evidence,download,onEdit}){
 const w=dateWindow(window),months=monthsInWindow(w),[metric,setMetric]=useState('total_amount'),[level,setLevel]=useState('parent'),definitions=level==='parent'?PARENTS:CHILDREN,matrix=categoryMonthRows(rows,leads,eligible,reported,w,combined,definitions),money=metric==='total_amount',colors=panelColors([{points:matrix.map(r=>({value:r[metric]??null}))}]);
 const note=notes.find(n=>n.category===category);
 return <section className="card category-trends" id="category-trends">
  <div className="section-heading"><div><h2>按月 × 按分类看趋势</h2><p>{level==='parent'?'5个父类':'14个子项'} · 点击格子查看去重后的相关记录</p></div><button className="button secondary" disabled={!onEdit} onClick={()=>download(`${w.start}_${w.end}_${level==='parent'?'父类':'子类'}_分类月度趋势.csv`,categoryMonthlyCsv(matrix),'text/csv;charset=utf-8')}>导出分类月表</button></div>
  <div className="trend-options"><label>分类层级<select aria-label="月度分类层级" value={level} onChange={e=>setLevel(e.target.value)}><option value="parent">父类 · 5个方向</option><option value="child">子类 · 14个观察项</option></select></label><label>观察指标<select aria-label="趋势观察指标" value={metric} onChange={e=>setMetric(e.target.value)}>{Object.entries(metrics).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><span>{money?'单位：人民币万元 · 区间按下限着色':'单位：独立事件数'} · 颜色越深，当前样本披露越多</span></div>
  <div className="table-scroll"><table className="trend-matrix"><caption className="sr-only">各分类{w.start}至{w.end}的{metrics[metric]}</caption><thead><tr><th scope="col">项目分类</th>{months.map(m=><th scope="col" key={m}>{monthLabel(m,w)}</th>)}</tr></thead><tbody>{Object.entries(definitions).map(([id,label])=><tr key={id} className={id===category?'selected-trend':''}><th scope="row"><button onClick={()=>onSelect(id,'all',metric)}>{label}</button>{level==='child'&&<small className="muted">{PARENTS[parentOf(id)]}</small>}</th>{matrix.filter(r=>r.category===id).map(r=>{const v=r[metric]??null,selected=id===category&&r.month===month,valueLabel=money&&r.total_amount_upper!==v?`${fmt(v)}—${fmt(r.total_amount_upper)}`:fmt(v);return <td key={r.month}><button aria-pressed={selected} aria-label={`${label} ${r.month} ${metrics[metric]} ${v==null?'未收录':valueLabel+(money?'万元':'')}，查看记录`} title={money?`${r.total_amount_count} 个去重金额项；合并披露 ${valueLabel} 万元`:`收录 ${r.records} 条 / ${r.events} 个事件`} onClick={()=>onSelect(id,r.month,metric)} style={{background:colors.background(v),color:'#284e81'}}>{money&&r.total_amount_upper!==v?<>{fmt(v)}<br/>—{fmt(r.total_amount_upper)}</>:fmt(v)}</button></td>;})}</tr>)}</tbody></table></div>
  <p className="footnote">色阶按当前表有效范围动态缩放：{fmt(colors.min)}—{fmt(colors.max)}{money?'万元':'个事件'}。{TAXONOMY_NOTE}</p><details><summary>分类与历史重算口径</summary><p className="footnote">{XPU_NOTE} 对全部已收录标题、事实摘要及芯片标签按同一规则识别；后续补采沿用相同分组，原始记录分类保留。分组覆盖当前关注清单，不代表穷尽全部服务器技术。事件数0表示当前样本未收录，金额“—”表示没有可合并披露额。</p></details>
  <p className="footnote">金额总图合并已核与待核、预算、成交、合同、投资、报价及预估，不受“证据范围”和“明细金额口径”影响；芯片、金额范围和搜索仍适用。同一项目/标包取最新披露一次并归入对应事件月，同日优先合同与成交；新披露可能修订历史格子。区间保留上下限，单价、无金额、已失效及冲突项不计。总图表示公开披露体量，不是实际成交额或市场规模；类别重叠，不跨行相加。“—”表示无可合并金额；*为非完整月，截至{w.end}。</p>
  <details className="research-record"><summary>原有技术主题趋势判断与行动建议</summary><div className="record-body"><p className="muted">以下保留已核样本的研究判断；金额总图合并核验状态，事件数按当前证据范围统计。</p>{notes.map(n=><article className="category-note" key={n.category}><h3>{TECHS[n.category]} · {n.trend}</h3><button className="text-button" disabled={!onEdit} onClick={()=>onEdit('category_notes',n.category,n)}>编辑分类判断</button><p><b>事实：</b>{n.findings}</p><p><b>判断：</b>{n.interpretation}</p><p><b>行动：</b>{n.action}</p><p className="footnote">{n.limitations}</p><button className="text-button" onClick={()=>onSelect(n.category,'all',metric)}>筛选此类全部月份记录 ↓</button><p>{(n.record_ids||[]).map(id=>{const e=evidence.find(r=>r.id===id);return e?<a key={id} href={safeUrl(e.url)||undefined} target="_blank" rel="noreferrer">{e.title} ↗　</a>:null;})}</p></article>)}</div></details>
  {note&&<div className="selected-category-note"><strong>{CLASS_LABELS[category]} · {note.trend}</strong><p>{note.findings}</p><p><b>判断与行动：</b>{note.interpretation} {note.action}</p><small>这是该类别研究归档判断；修订台账后需复核，不随筛选或记录修改自动重写。{note.limitations}</small></div>}
 </section>;
}
