'use client';
import {useEffect,useState} from 'react';
import TrendBarChart from './trend-bar-chart';
import {TECHS,safeUrl,dateWindow,monthsInWindow,monthLabel} from '@/lib/model';
import {PARENTS,CHILDREN,CLASS_LABELS,childIds,parentOf,observationCategories} from '@/lib/hierarchy';
import {CHIPS} from '@/lib/monthly';
import {PANEL_METRICS,panelMatrix,panelCsv,perMille,panelColors} from '@/lib/panel';

function Select({label,value,onChange,options}){return <label>{label}<select aria-label={label} value={value} onChange={e=>onChange(e.target.value)}>{Object.entries(options).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>;}
function save(name,text,type){const u=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function Value({p}){return <><strong>{p.value==null?'—':p.u?`${p.value.toFixed(1)}–${p.upper.toFixed(1)}‰`:perMille(p.value)}</strong><small>{p.complete?`${p.n}/${p.N}${p.u?` · ?${p.u}`:''}`:`已读 ${p.n}/${p.N} · 缺口`}</small></>;}
function Tip({active,payload}){if(!active||!payload?.length)return null;const p=payload[0].payload;return <div className="panel-tooltip"><b>{p.id}{p.partial?' · 非完整时期':''}</b><p>明确命中 {p.n} / 分母新闻／样本 {p.N}</p>{p.u>0&&<p>条款未判定 {p.u}，比例范围{perMille(p.value)}—{perMille(p.upper)}</p>}<p>明确比例 {perMille(p.value)}</p><p>{p.status}</p></div>;}
export default function MarketPanel(){
 const [data,setData]=useState(null),[error,setError]=useState(''),[metric,setMetric]=useState('attention'),[sourceId,setSourceId]=useState(''),[level,setLevel]=useState('parent'),[category,setCategory]=useState('facilities'),[frequency,setFrequency]=useState('month'),[chip,setChip]=useState('all'),[period,setPeriod]=useState('all'),[evidenceScope,setEvidenceScope]=useState('numerator');
 useEffect(()=>{let active=true;fetch('/market-panel.json').then(r=>{if(!r.ok)throw Error('固定样本数据暂时无法读取');return r.json();}).then(d=>{if(active)setData({...d,documents:d.documents.map(r=>({...r,observation_categories:observationCategories(r,'news')}))});}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[]);
 if(error)return <p className="notice error" role="alert">{error}</p>;
 if(!data)return <p className="notice">正在读取固定样本与覆盖记录…</p>;
 const sources=data.sources.filter(s=>s.kind===(metric==='demand'?'procurement':'news')&&(metric!=='application'||s.application_reviewed!==false)),source=sources.find(s=>s.id===sourceId)||sources[0];
 if(!source)return <p className="notice">当前尚未取得这一口径的固定样本。</p>;
 const definitions=level==='parent'?PARENTS:CHILDREN,matrix=panelMatrix(data,source,metric,frequency,chip,definitions),focus=matrix.find(r=>r.id===category)||matrix[0],selected=focus.points.filter(p=>period==='all'||p.id===period),ids=new Set(selected.flatMap(p=>evidenceScope==='denominator'?p.denominator_ids:evidenceScope==='unknown'?p.unknown_ids:p.ids)),docs=data.documents.filter(r=>ids.has(r.id));
 const colors=panelColors(matrix),window=dateWindow(data.window),months=monthsInWindow(window);
 const completePoints=focus.points.filter(p=>p.value!==null&&!p.partial),first=completePoints[0],last=completePoints.at(-1),comparableChange=first&&last&&first.id!==last.id&&!first.u&&!last.u&&first.N>=10&&last.N>=10?last.value-first.value:null;
 const readout=comparableChange===null?'覆盖、条款或样本量不足，暂不判断趋势。':`${first.label}—${last.label}：样本比例${comparableChange>=0?'增加':'减少'}${Math.abs(comparableChange).toFixed(1)}个千分点（${first.n}/${first.N} → ${last.n}/${last.N}）。`;
 const reset=()=>{setSourceId('');setChip('all');setPeriod('all');setEvidenceScope('numerator');setFrequency('month');};
 return <div className="market-panel">
  <div className="panel-tabs" role="group" aria-label="观测口径">{Object.entries(PANEL_METRICS).map(([id,label])=><button key={id} aria-pressed={metric===id} className={metric===id?'selected':''} onClick={()=>{setMetric(id);reset();}}><b>{label}</b></button>)}</div>
  <section className="card panel-controls"><div className="source-filters"><Select label="市场分类层级" value={level} onChange={v=>{setLevel(v);setCategory(v==='parent'?(parentOf(category)||category):(PARENTS[category]?childIds(category)[0]:category));setPeriod('all');}} options={{parent:'父类 · 5个方向',child:'子类 · 14个观察项'}}/><Select label="固定样本来源" value={source.id} onChange={v=>{setSourceId(v);setPeriod('all');}} options={Object.fromEntries(sources.map(s=>[s.id,s.name]))}/><Select label="统计周期" value={frequency} onChange={v=>{setFrequency(v);setPeriod('all');}} options={{month:'按月',quarter:'按季度合并'}}/><Select label="分子中的芯片路线" value={chip} onChange={setChip} options={{all:'不限芯片',hyg_cpu:CHIPS.hyg_cpu,hyg_dcu:CHIPS.hyg_dcu,kunpeng:CHIPS.kunpeng}}/></div><div className="panel-actions"><span>{window.start} 至 {window.end} · * 非完整时期</span><button className="text-button" onClick={reset}>重置筛选</button><button className="text-button" onClick={()=>save('固定样本_当前口径.csv',panelCsv(matrix),'text/csv;charset=utf-8')}>导出当前表格</button></div></section>
  {metric==='attention'&&<section className="card"><details open><summary><b>已接入新闻来源 · 按月完整分母</b></summary><div className="table-scroll"><table><thead><tr><th>来源与范围</th>{months.map(m=><th key={m}>{monthLabel(m,window)}</th>)}<th>合计</th></tr></thead><tbody>{data.sources.filter(s=>['media','official'].includes(s.group)&&!s.document_source_id).map(s=><tr key={s.id}><th><button className="text-button" onClick={()=>{setSourceId(s.id);setPeriod('all');}}>{s.name}{s.group==='official'?'（官网）':''}</button></th>{months.map(m=>{const c=s.coverage.find(c=>c.month===m);return <td key={m}>{c?.eligible?.toLocaleString('zh-CN')??'—'}{c?.status!=='complete'?'*':''}</td>;})}<td><b>{s.coverage.reduce((n,c)=>n+(c.eligible||0),0).toLocaleString('zh-CN')}</b></td></tr>)}</tbody></table></div><p className="panel-note">* 覆盖不完整或沿用旧数据</p></details></section>}
  <section className="card"><div className="section-heading"><div><h2>{level==='parent'?'5个父类':'14个子项'} · {PANEL_METRICS[metric]}</h2><p>‰ · n/N</p></div></div><div className="table-scroll"><table className="panel-matrix"><thead><tr><th>技术</th>{focus.points.map(p=><th key={p.id}>{p.label}</th>)}</tr></thead><tbody>{matrix.map(c=><tr key={c.id}><th><button onClick={()=>{setCategory(c.id);setPeriod('all');}} aria-pressed={category===c.id}>{c.name}</button>{level==='child'&&<small>{PARENTS[parentOf(c.id)]}</small>}</th>{c.points.map(p=><td key={p.id}><button onClick={()=>{setCategory(c.id);setPeriod(p.id);}} aria-pressed={category===c.id&&period===p.id} aria-label={`${c.name} ${p.id} ${p.status} ${p.n}/${p.N}${p.u?' 含未知'+p.u:''}`} style={{background:colors.background(p.value),color:'#16375b',borderStyle:p.partial?'dashed':'solid'}}><Value p={p}/></button></td>)}</tr>)}</tbody></table></div><p className="panel-note panel-scale"><span>色阶：{perMille(colors.min)}</span><i aria-hidden="true" style={{background:colors.min===null?"#f1f3f6":`linear-gradient(to right, ${colors.background(colors.min)}, ${colors.background(colors.max)})`}}/><span>{perMille(colors.max)}</span></p><p className="panel-note">— 缺口 · 0‰ 无命中 · ? 条款待判 · * 非完整时期</p></section>
  <section className="card"><div className="section-heading"><div><h2>{CLASS_LABELS[category]} · {metric==='demand'?'采购技术要求比例趋势':'技术提及比例趋势'}</h2></div><Select label="查看技术" value={category} onChange={v=>{setCategory(v);setPeriod('all');}} options={definitions}/></div>{focus.points.some(p=>p.value!==null)?<TrendBarChart data={focus.points} yAxis={{domain:[0,max=>Math.max(1,Math.ceil(max*1.15))],tickFormatter:v=>v+'‰'}} tooltip={{content:<Tip/>}} bars={[{dataKey:'value',name:metric==='demand'?'明确要求':'明确提及',fill:'#376fe5',stackId:'share'},...(metric==='demand'?[{dataKey:'unknown',name:'条款未判定',fill:'#d5a44b',stackId:'share'}]:[])]}/>:<p className="notice">覆盖不足，暂不显示比例趋势。</p>}<div className="panel-sizes">{focus.points.map(p=><span key={p.id}>{p.label}：{`${p.n}/${p.N}${p.u?`（?${p.u}）`:''}${p.complete?'':' · 仅已读'}`}</span>)}</div><p className="panel-reading">{readout}</p></section>
  <section className="card"><div className="section-heading"><div><h2>分子与分母明细</h2></div></div><div className="source-filters"><Select label="证据时期" value={period} onChange={setPeriod} options={{all:'全部时期',...Object.fromEntries(focus.points.map(p=>[p.id,p.label]))}}/><Select label="查看样本" value={evidenceScope} onChange={setEvidenceScope} options={{numerator:'分子：明确命中',denominator:metric==='demand'?'分母：全部适用标包':'分母：全部去重新闻',unknown:'条款未判定'}}/></div><p className="panel-note">当前 {docs.length} 条 · {CLASS_LABELS[category]}</p>{docs.slice(0,100).map(r=><details className="panel-record" key={r.id}><summary><b>{r.title}</b><small>{r.date} · {r.publisher||source.name}{r.context_class==='application'?' · 标题含采购或部署表述':''}</small></summary><div><p>{r.classification_note||r.excerpt||r.summary}</p>{r.amount_cny!=null&&<p>预算或披露额：{(r.amount_cny/1e4).toLocaleString('zh-CN')}万元</p>}<p>{metric==='demand'?`适用分母：${r.eligible_categories.map(c=>TECHS[c]).join('、')||'无'}；明确要求：${r.required_categories.map(c=>TECHS[c]).join('、')||'未明示'}`:`标题标签：${r.observation_categories.map(c=>CLASS_LABELS[c]).join('、')||'普通内容分母'}`}</p>{metric==='demand'&&<p>所选技术条款：{childIds(category).some(c=>r.required_categories.includes(c))?'明确要求':childIds(category).some(c=>r.unknown_categories.includes(c))?'未知（不能视为未要求）':childIds(category).some(c=>r.eligible_categories.includes(c))?'未明确要求':'适用分母未建立'}。{r.requirement_quote?.[category]}</p>}<a href={safeUrl(r.url)||undefined} target="_blank" rel="noreferrer">阅读原文 ↗</a></div></details>)}{!docs.length&&<p className="panel-note">当前没有匹配文档。</p>}{docs.length>100&&<p>显示前 100 条</p>}</section>
  <section className="card"><details className="panel-coverage"><summary>来源覆盖</summary><div className="table-scroll"><table><thead><tr><th>月份</th><th>采集文档</th><th>{metric==='demand'?'适用需求':'全部去重新闻'}</th><th>覆盖</th><th>截至</th></tr></thead><tbody>{source.coverage.map(c=><tr key={c.month}><td>{c.month}</td><td>{c.total??'—'}</td><td>{c.eligible??'—'}</td><td>{c.status==='complete'?'本窗口覆盖已核对':c.status==='stale'?'沿用旧数据，暂不可比':c.status==='missing'?'未取得完整数据':'不完整 / 未建立'}</td><td>{c.covered_through||'—'}</td></tr>)}</tbody></table></div><a href={source.url} target="_blank" rel="noreferrer">固定来源入口 ↗</a><p className="panel-note">采集：{data.collected_at}</p><a className="text-button" href="/market-panel.json" download>下载指标依据与样本明细</a></details></section>
 </div>;
}
