'use client';
import {useEffect,useState} from 'react';
import {BarChart,Bar,Cell,XAxis,YAxis,Tooltip,Legend,ResponsiveContainer,CartesianGrid} from 'recharts';
import {TECHS,safeUrl,dateWindow,monthsInWindow,monthLabel} from '@/lib/model';
import {PARENTS,CHILDREN,CLASS_LABELS,childIds,parentOf,TAXONOMY_NOTE,XPU_NOTE,observationCategories} from '@/lib/hierarchy';
import {CHIPS} from '@/lib/monthly';
import {PANEL_METRICS,PANEL_DEFINITIONS,panelMatrix,panelCsv,perMille,panelColors} from '@/lib/panel';

function Select({label,value,onChange,options}){return <label>{label}<select aria-label={label} value={value} onChange={e=>onChange(e.target.value)}>{Object.entries(options).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>;}
function save(name,text,type){const u=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function Value({p}){return <><strong>{p.value==null?'—':p.u?`${p.value.toFixed(1)}–${p.upper.toFixed(1)}‰`:perMille(p.value)}</strong><small>{p.complete?`${p.n}/${p.N}${p.u?` · ?${p.u}`:''}`:`已读 ${p.n}/${p.N} · 缺口`}</small></>;}
function Tip({active,payload}){if(!active||!payload?.length)return null;const p=payload[0].payload;return <div className="panel-tooltip"><b>{p.id}{p.partial?' · 非完整时期':''}</b><p>明确命中 {p.n} / 分母新闻／样本 {p.N}</p>{p.u>0&&<p>条款未判定 {p.u}，比例范围{perMille(p.value)}—{perMille(p.upper)}</p>}<p>明确比例 {perMille(p.value)}</p><p>{p.status}</p></div>;}
export default function MarketPanel(){
 const [data,setData]=useState(null),[error,setError]=useState(''),[metric,setMetric]=useState('attention'),[sourceId,setSourceId]=useState(''),[level,setLevel]=useState('parent'),[category,setCategory]=useState('facilities'),[frequency,setFrequency]=useState('month'),[chip,setChip]=useState('all'),[period,setPeriod]=useState('all'),[evidenceScope,setEvidenceScope]=useState('numerator');
 useEffect(()=>{let active=true;fetch('/market-panel.json').then(r=>{if(!r.ok)throw Error('固定样本数据暂时无法读取');return r.json();}).then(d=>{if(active)setData({...d,documents:d.documents.map(r=>({...r,observation_categories:observationCategories(r,'news')}))});}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[]);
 if(error)return <p className="notice error" role="alert">{error}</p>;
 if(!data)return <p className="notice">正在读取固定样本与覆盖记录…</p>;
 const sources=data.sources.filter(s=>s.kind===(metric==='demand'?'procurement':'news')&&(metric!=='application'||s.application_reviewed!==false)),source=sources.find(s=>s.id===sourceId)||sources[0];
 if(!source)return <p className="notice">当前尚未取得这一口径的固定样本。</p>;
 const definitions=level==='parent'?PARENTS:CHILDREN,matrix=panelMatrix(data,source,metric,frequency,chip,definitions),focus=matrix.find(r=>r.id===category)||matrix[0],selected=focus.points.filter(p=>period==='all'||p.id===period),ids=new Set(selected.flatMap(p=>evidenceScope==='denominator'?p.denominator_ids:evidenceScope==='unknown'?p.unknown_ids:p.ids)),docs=data.documents.filter(r=>ids.has(r.id));
 const colors=panelColors(matrix),window=dateWindow(data.window),months=monthsInWindow(window);
 const completePoints=focus.points.filter(p=>p.value!==null&&!p.partial),first=completePoints[0],last=completePoints.at(-1),comparableChange=first&&last&&first.id!==last.id&&!first.u&&!last.u&&first.N>=10&&last.N>=10?last.value-first.value:null;
 const readout=comparableChange===null?'当前类别的完整时期、条款判定或分母规模不足以给出稳定方向；先核对分母与未知条款。':`${first.label}至${last.label}，该固定样本中的明确比例${comparableChange>=0?'增加':'减少'}${Math.abs(comparableChange).toFixed(1)}个千分点（${first.n}/${first.N} → ${last.n}/${last.N}）。这描述样本结构，不代表全国市场增速。`;
 const reset=()=>{setSourceId('');setChip('all');setPeriod('all');setEvidenceScope('numerator');setFrequency('month');};
 return <div className="market-panel">
  <div className="panel-tabs" role="group" aria-label="观测口径">{Object.entries(PANEL_METRICS).map(([id,label])=><button key={id} aria-pressed={metric===id} className={metric===id?'selected':''} onClick={()=>{setMetric(id);reset();}}><b>{label}</b><span>{id==='demand'?'买方技术要求':id==='application'?'报道中的应用表述':'行业关注方向'}</span></button>)}</div>
  <section className="card panel-controls"><div className="source-filters"><Select label="市场分类层级" value={level} onChange={v=>{setLevel(v);setCategory(v==='parent'?(parentOf(category)||category):(PARENTS[category]?childIds(category)[0]:category));setPeriod('all');}} options={{parent:'父类 · 5个方向',child:'子类 · 14个观察项'}}/><Select label="固定样本来源" value={source.id} onChange={v=>{setSourceId(v);setPeriod('all');}} options={Object.fromEntries(sources.map(s=>[s.id,s.name]))}/><Select label="统计周期" value={frequency} onChange={v=>{setFrequency(v);setPeriod('all');}} options={{month:'按月',quarter:'按季度合并'}}/><Select label="分子中的芯片路线" value={chip} onChange={setChip} options={{all:'不限芯片',hyg_cpu:CHIPS.hyg_cpu,hyg_dcu:CHIPS.hyg_dcu,kunpeng:CHIPS.kunpeng}}/></div><p>{PANEL_DEFINITIONS[metric]}{chip!=='all'&&` 分子进一步限定明确提及${CHIPS[chip]}，分母不变。`}</p><div className="panel-actions"><span>{window.start} 至 {window.end} · *为非完整时期</span><button className="text-button" onClick={reset}>重置筛选</button><button className="text-button" onClick={()=>save('固定样本_当前口径.csv',panelCsv(matrix),'text/csv;charset=utf-8')}>导出当前表格</button></div></section>
  {metric==='attention'&&<section className="card"><details open><summary><b>已接入新闻来源 · 按月完整分母</b></summary><p className="panel-note">每行是一家出版方的固定新闻归档；同源去重，所有主题保留。点击来源可单独核对趋势。官网不计入媒体合计。</p><div className="table-scroll"><table><thead><tr><th>来源与范围</th>{months.map(m=><th key={m}>{monthLabel(m,window)}</th>)}<th>合计</th></tr></thead><tbody>{data.sources.filter(s=>['media','official'].includes(s.group)&&!s.document_source_id).map(s=><tr key={s.id}><th><button className="text-button" onClick={()=>{setSourceId(s.id);setPeriod('all');}}>{s.name}{s.group==='official'?'（官网）':''}</button></th>{months.map(m=>{const c=s.coverage.find(c=>c.month===m);return <td key={m}>{c?.eligible?.toLocaleString('zh-CN')??'—'}{c?.status!=='complete'?'*':''}</td>;})}<td><b>{s.coverage.reduce((n,c)=>n+(c.eligible||0),0).toLocaleString('zh-CN')}</b></td></tr>)}</tbody></table></div><p className="panel-note">* 官网带星号的月份覆盖不完整，仅显示已取得条目。{data.unavailable_sources?.map(s=>`${s.name}：${s.reason}`).join(' ')}</p></details></section>}
  <details className="card"><summary>父子分类与重算口径</summary><p>{TAXONOMY_NOTE}</p><p>{XPU_NOTE}</p><p>新闻全量标题按同一规则重算全部月份，分母仍为固定来源全部新闻。这是分类重算，没有增加新闻篇数；不等同于新增专项检索。采购中新路线适用分母未建立，相关父类也不输出完整比例。新增主题的采购/部署标题行为尚未完整复核，该指标保留缺口，不显示0比例。</p></details>
  <div className="panel-context"><strong>{source.scope}</strong><p>{source.limitation}</p>{metric!=='demand'&&<p>各月统一只读取标题中的技术与行为表述；没有出现在标题，不等于正文未讨论或市场未采用。</p>}</div>
  <section className="card"><div className="section-heading"><div><h2>{level==='parent'?'5个父类':'14个子项'} · {PANEL_METRICS[metric]}</h2><p>每格显示千分数（‰）与分子／分母；点击查看明细。类别可重叠，不跨行相加。</p></div></div><div className="table-scroll"><table className="panel-matrix"><thead><tr><th>技术</th>{focus.points.map(p=><th key={p.id}>{p.label}</th>)}</tr></thead><tbody>{matrix.map(c=><tr key={c.id}><th><button onClick={()=>{setCategory(c.id);setPeriod('all');}} aria-pressed={category===c.id}>{c.name}</button>{level==='child'&&<small>{PARENTS[parentOf(c.id)]}</small>}</th>{c.points.map(p=><td key={p.id}><button onClick={()=>{setCategory(c.id);setPeriod(p.id);}} aria-pressed={category===c.id&&period===p.id} aria-label={`${c.name} ${p.id} ${p.status} ${p.n}/${p.N}${p.u?' 含未知'+p.u:''}`} style={{background:colors.background(p.value),color:'#16375b',borderStyle:p.partial?'dashed':'solid'}}><Value p={p}/></button></td>)}</tr>)}</tbody></table></div><p className="panel-note panel-scale"><span>色阶：{perMille(colors.min)}</span><i aria-hidden="true" style={{background:colors.min===null?"#f1f3f6":`linear-gradient(to right, ${colors.background(colors.min)}, ${colors.background(colors.max)})`}}/><span>{perMille(colors.max)}</span><span>按当前来源、周期和芯片筛选的有效数据范围自动缩放；当前表共用色阶。</span></p><p className="panel-note">“—”表示覆盖不完整或没有适用分母；0‰表示本样本已判定但没有明确命中。“?”表示条款待判，显示最低—最高可能比例。采购各技术适用分母不同，只比较自身历史；覆盖缺口时的n/N仅为已读样本，不是完整比例。</p></section>
  <section className="card"><div className="section-heading"><div><h2>{CLASS_LABELS[category]} · {metric==='demand'?'采购技术要求比例趋势':'技术提及比例趋势'}</h2><p>{source.denominators?.[category]||PANEL_DEFINITIONS[metric]}</p></div><Select label="查看技术" value={category} onChange={v=>{setCategory(v);setPeriod('all');}} options={definitions}/></div>{focus.points.some(p=>p.value!==null)?<div className="panel-plot"><ResponsiveContainer width="100%" height="100%"><BarChart data={focus.points} margin={{top:15,left:0,right:12,bottom:0}} accessibilityLayer><CartesianGrid vertical={false} strokeDasharray="3 3"/><XAxis dataKey="label" tick={{fontSize:13}}/><YAxis domain={[0,max=>Math.max(1,Math.ceil(max*1.15))]} tickFormatter={v=>v+'‰'} width={62} tick={{fontSize:13}}/><Tooltip content={<Tip/>}/><Legend wrapperStyle={{fontSize:13}}/>{[['value',metric==='demand'?'明确要求':'明确提及','#286ac5'],...(metric==='demand'?[['unknown','条款未判定','#d3a84b']]:[])].map(([key,name,color])=><Bar key={key} dataKey={key} name={name} fill={color} stackId="share" isAnimationActive={false}>{focus.points.map(p=><Cell key={p.id} fillOpacity={p.partial ? .5 : 1} stroke={p.partial?color:undefined} strokeDasharray={p.partial?'3 3':undefined}/>)}</Bar>)}</BarChart></ResponsiveContainer></div>:<p className="notice">当前来源未满足比例图的覆盖条件。下方保留已读样本中的命中数／适用数；补齐正文和历史覆盖后才能比较趋势。</p>}<div className="panel-sizes">{focus.points.map(p=><span key={p.id}>{p.label}：{`${p.n}/${p.N}${p.u?`（?${p.u}）`:''}${p.complete?'':' · 仅已读'}`}</span>)}</div><p className="panel-reading">{readout}</p><p className="panel-note">先核对采购条款或标题原文，再判断是否值得跟进客户。没有明确要求某技术，不等于排斥该技术。小样本可切换季度查看合并分母；N≥10只用于抑制极小样本自动读数，不是统计显著性标准。</p></section>
  <section className="card"><div className="section-heading"><div><h2>分子与分母明细</h2><p>查看原文与分类依据；新闻分母保留全站全部去重新闻；采购分母保留适用标包，未知条款单列。项目金额另见“月度研究”。</p></div></div><div className="source-filters"><Select label="证据时期" value={period} onChange={setPeriod} options={{all:'全部时期',...Object.fromEntries(focus.points.map(p=>[p.id,p.label]))}}/><Select label="查看样本" value={evidenceScope} onChange={setEvidenceScope} options={{numerator:'分子：明确命中',denominator:metric==='demand'?'分母：全部适用标包':'分母：全部去重新闻',unknown:'条款未判定'}}/></div><p className="panel-note">当前 {docs.length} 条 · {CLASS_LABELS[category]}</p>{docs.slice(0,100).map(r=><details className="panel-record" key={r.id}><summary><b>{r.title}</b><small>{r.date} · {r.publisher||source.name}{r.context_class==='application'?' · 标题含采购或部署表述':''}</small></summary><div><p>{r.classification_note||r.excerpt||r.summary}</p>{r.amount_cny!=null&&<p>预算或披露额：{(r.amount_cny/1e4).toLocaleString('zh-CN')}万元；仅代表该文档金额口径。</p>}<p>{metric==='demand'?`适用分母：${r.eligible_categories.map(c=>TECHS[c]).join('、')||'无'}；明确要求：${r.required_categories.map(c=>TECHS[c]).join('、')||'未明示'}`:`标题标签：${r.observation_categories.map(c=>CLASS_LABELS[c]).join('、')||'未命中观察主题，保留为普通内容分母'}`}</p>{metric==='demand'&&<p>所选技术条款：{childIds(category).some(c=>r.required_categories.includes(c))?'明确要求':childIds(category).some(c=>r.unknown_categories.includes(c))?'未知（不能视为未要求）':childIds(category).some(c=>r.eligible_categories.includes(c))?'未明确要求':'适用分母未建立'}。{r.requirement_quote?.[category]}</p>}<a href={safeUrl(r.url)||undefined} target="_blank" rel="noreferrer">阅读原文 ↗</a></div></details>)}{!docs.length&&<p className="panel-note">当前没有匹配文档。</p>}{docs.length>100&&<p>仅展示前100条，完整条目见下方样本文件。</p>}</section>
  <section className="card"><details className="panel-coverage"><summary>来源覆盖与采样规则</summary><p>{source.method}</p><div className="table-scroll"><table><thead><tr><th>月份</th><th>采集文档</th><th>{metric==='demand'?'适用需求':'全部去重新闻'}</th><th>覆盖</th><th>说明</th></tr></thead><tbody>{source.coverage.map(c=><tr key={c.month}><td>{c.month}</td><td>{c.total??'—'}</td><td>{c.eligible??'—'}</td><td>{c.status==='complete'?'本窗口覆盖已核对':'不完整 / 未建立'}</td><td>{c.note}</td></tr>)}</tbody></table></div><a href={source.url} target="_blank" rel="noreferrer">固定来源入口 ↗</a><p className="panel-note">采集时间：{data.collected_at}。历史事件库另行维护，单条补录不会改变此固定样本分母。</p><a className="text-button" href="/market-panel.json" download>下载指标依据与样本明细</a></details></section>
 </div>;
}
