'use client';
import {useState,useMemo} from 'react';
import {BarChart,Bar,XAxis,YAxis,CartesianGrid,Tooltip,Legend,ResponsiveContainer} from 'recharts';
import {Download,ArrowUpRight} from 'lucide-react';

import CategoryTrends from './category-trends';
import {TECHS,STAGES,SCOPES,REVIEWS,safeUrl,researchReview,dateWindow,monthsInWindow,partialMonth} from '@/lib/model';
import {AMOUNTS,CHIPS,inObservationPeriod,inResearchPeriod,amountRows,reportedAmountRows,combinedAmountRows,monthlyDisclosureRows,monthlySeries,eventKey,monthOf,ledgerCsv} from '@/lib/monthly';
import {CHILDREN,CLASS_LABELS,matchesCategory,matchesChip,observationCategories} from '@/lib/hierarchy';
const fmt=n=>n==null?'—':n.toLocaleString('zh-CN',{maximumFractionDigits:2});
const recordAmount=e=>e.amount_range_cny?`${fmt(e.amount_range_cny.min/1e8)}—${fmt(e.amount_range_cny.max/1e8)} 亿元（预计）`:e.amount_cny==null?'金额未披露 / 待核':`¥${fmt(e.amount_cny)}`;
function download(name,content,type){const u=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function Select({label,value,onChange,options}){return <label>{label}<select aria-label={label} value={value} onChange={e=>onChange(e.target.value)}>{Object.entries(options).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>;}
const reviewLabel={promote:'转入核验',retain:'继续待核',exclude:'范围外保留'};
function ReviewResult({entry:e}){return <><p><b>{e.checked_at} 复核：</b>{reviewLabel[e.decision]}。{e.reason}</p>{!!e.unresolved?.length&&<p><b>未解决：</b>{e.unresolved.join('；')}</p>}<p><b>下一步：</b>{e.next_action}</p>{(e.sources||[]).map((s,i)=><p key={i}><a href={safeUrl(s.url)||undefined} target="_blank" rel="noreferrer">{s.publisher||'核查来源'} ↗</a> · {{fulltext:'正文已读',snippet:'仅索引/摘要',unavailable:'本次无法读取'}[s.read_status]||s.read_status} · {s.finding}</p>)}</>;}
function Sources({record:e}){return <><p><b>核查状态：</b>{e.evidence_status==='primary'?'原始披露正文已读':e.evidence_status==='reported'?'报道正文已读，待原始披露确认':e.evidence_status==='conflict'?'存在冲突，金额隔离':e.evidence_status==='lead'?(e.verified_fulltext?'正文已读，其他核查条件未满足':'索引 / 局部线索，待核原文'):'正文已读（保留发布者角色）'}　{e.source_read_result}</p>{e.service_duration_months&&<p><b>服务期：</b>{e.service_duration_months} 个月　{e.service_start_basis}　{e.payment_terms}</p>}{e.tag_qualifiers&&<p><b>选型限制：</b>{Object.values(e.tag_qualifiers).join('；')}</p>}{e.wechat_account&&<p><b>公众号：</b>{e.wechat_account}</p>}{(e.corroborating_sources||[]).map((s,i)=><p key={i}><a href={safeUrl(s.url)||undefined} target="_blank" rel="noreferrer">{s.publisher||s.title||'关联来源'} ↗</a>　{s.relationship} · {s.read_status}{s.independent===false?' · 同源，不算独立验证':''}</p>)}{e.lineage&&<p className="footnote">来源链：{e.lineage}</p>}</>;}
export default function MonthlyResearch({research,onEdit}){
 const [category,setCategory]=useState('all'),[chip,setChip]=useState('all'),[kind,setKind]=useState('award'),[month,setMonth]=useState('all'),[query,setQuery]=useState(''),[amountScope,setAmountScope]=useState('all'),[evidenceScope,setEvidenceScope]=useState('all');
 const window=dateWindow(research),months=monthsInWindow(window),isObserved=e=>inObservationPeriod(e,window),isVerified=e=>inResearchPeriod(e,window),rangeLabel=`${window.start} 至 ${window.end}`,filePrefix=`${window.start}_${window.end}`;
 const allRecords=useMemo(()=>[...research.events.map(e=>({...e,_section:'events'})),...research.leads.map(e=>({...e,_section:'leads'}))].map(e=>({...e,observation_categories:observationCategories(e)})),[research]);
 const period=allRecords.filter(isObserved),verified=period.filter(isVerified),pending=period.filter(e=>researchReview(e)!=='accepted'),history=allRecords.filter(e=>!isObserved(e));
 const scopeMatches=e=>evidenceScope==='all'||(evidenceScope==='pending'?researchReview(e)!=='accepted':researchReview(e)===evidenceScope),included=period.filter(scopeMatches);
 const editButton=(section,key,e)=><button className="text-button" disabled={!onEdit} onClick={()=>onEdit(e._section||section,key,e)}>编辑{section==='events'?'台账':section==='leads'?'线索':'判断'}</button>;
 function addRow(section){const id=crypto.randomUUID();onEdit(section,id,{id,title:'',url:'',publisher:'',customer:'',project_id:id,event_key:id,published_date:'',event_date:null,stage:'research',source_type:'unknown',categories:[],tags:[],amount_cny:null,amount_kind:'none',amount_scope:'unknown',amount_text:'',fact_summary:'',limitations:'',verified_fulltext:false,amount_eligible:false,evidence_status:section==='events'?'primary':'lead',_revision:0});}
 const baseMatches=e=>(amountScope==='all'||e.amount_scope===amountScope)&&matchesChip(e,chip)&&(!query||[e.title,e.customer,e.publisher,e.fact_summary,e.project_id,e.wechat_account].join(' ').toLowerCase().includes(query.toLowerCase()));
 const matches=e=>baseMatches(e)&&matchesCategory(e,category);
 const matching=included.filter(matches),matchingLeads=matching.filter(e=>researchReview(e)!=='accepted'),leads=matchingLeads.filter(e=>month==='all'||monthOf(e)===month);
 const eligible=amountRows(period),reported=reportedAmountRows(period),reportedSeries=monthlySeries(matching,kind,reported,window),verifiedSeries=monthlySeries(matching.filter(isVerified),kind,eligible,window);
 const series=monthlySeries(matching,kind,eligible,window).map((s,i)=>({...s,verified_events:verifiedSeries[i].events,leads:matchingLeads.filter(e=>monthOf(e)===s.month).length,reported_amount:reportedSeries[i].amount})),disclosures=monthlySeries(matching,kind,monthlyDisclosureRows(verified,window),window).map((s,i)=>({...s,reported_amount:reportedSeries[i].amount})),rows=matching.filter(e=>month==='all'||monthOf(e)===month).sort((a,b)=>(b.event_date||b.published_date).localeCompare(a.event_date||a.published_date));
 function selectCell(c,m,metric){setCategory(c);setMonth(m);if(metric==='total_amount')setEvidenceScope('all');document.getElementById('monthly-records')?.scrollIntoView({behavior:'smooth',block:'start'});}
 const selectedAmounts=eligible.filter(e=>rows.some(r=>r.id===e.id)&&e.amount_kind===kind),sum=selectedAmounts.length?selectedAmounts.reduce((s,e)=>s+e.amount_cny,0)/1e4:null;
 const selectedReported=reported.filter(e=>rows.some(r=>r.id===e.id)&&e.amount_kind===kind),reportedSum=selectedReported.length?selectedReported.reduce((s,e)=>s+e.amount_cny,0)/1e4:null;
 const count=new Set(rows.map(eventKey)).size,coverage=new Set(research.queries.filter(q=>CHILDREN[q.category]&&months.includes(q.month)).map(q=>q.category+'|'+q.month)).size;
 return <div className="monthly-research">
  <div className="notice"><span><strong>{rangeLabel} · 已收录 {period.length} 条：已核 {verified.length} 条，待核及冲突 {pending.length} 条 · 窗口外或日期待定 {history.length} 条</strong><br/>默认纳入新闻、公众号、索引与待核线索；记录保留核验状态。{months.length}个月观察窗口，按事件日（未明示则披露日）归月。搜索覆盖不等于市场全量覆盖；未核得记录不能解释为没有需求。{research.recheck&&<><br/><a href="#lead-review">{research.recheck.checked_at} 已逐条复核 {research.recheck.entries.length} 条待处理记录，查看结果 ↓</a></>}</span></div>
  {research.rolling_update&&<div className="soft-note"><p>{research.rolling_update.summary}</p>{research.rolling_update.insights?.map(i=><p key={i.title}><b>{i.title}：</b>{i.text} <a href={safeUrl(i.url)||undefined} target="_blank" rel="noreferrer">依据 ↗</a></p>)}</div>}
  {research.source_remediation&&<p className="soft-note">{research.source_remediation.summary}</p>}
  {research.expansion&&<p className="footnote">{research.expansion.summary} 扩样增加的是历史收录量，不是市场新增需求；产品发布、生态适配与采购、投产分别保留阶段。来源清单见“来源与采集”，完整记录随研究包导出。</p>}
  {research.recheck&&<section className="card" id="lead-review"><div className="section-heading"><div><h2>待核线索逐条复核</h2><p>{research.recheck.scope} · 转入核验 {research.recheck.entries.filter(e=>e.decision==='promote').length} 条，继续待核 {research.recheck.entries.filter(e=>e.decision==='retain').length} 条。核查日为{research.recheck.checked_at}，本段为当次复核归档。</p></div><button className="button secondary" onClick={()=>download('20260921_待核线索复核记录.json',JSON.stringify(research.recheck,null,2),'application/json')}>导出复核记录</button></div><p className="footnote">复核成功不等于成交：候选报价、框架上限和合同预计区间仍不计确定金额。以下保留本次复核时的结论及来源；站内后续编辑不会改写本次复核记录。</p><details className="research-record"><summary>逐条查看本次全部 {research.recheck.entries.length} 条核查结果</summary><div className="record-body">{research.recheck.entries.map(e=><details className="research-record" key={e.id}><summary>{e.title} · {reviewLabel[e.decision]}</summary><div className="record-body"><ReviewResult entry={e}/></div></details>)}</div></details></section>}
  <section className="card monthly-controls"><div className="source-filters"><Select label="证据范围" value={evidenceScope} onChange={setEvidenceScope} options={{all:'全部收录（含待核）',accepted:'仅已核验',pending:'待核与冲突',quarantine:'仅冲突记录'}}/><Select label="项目分类" value={category} onChange={setCategory} options={{all:'全部（含芯片采购补充）',...CLASS_LABELS}}/><Select label="芯片路线" value={chip} onChange={setChip} options={{all:'全部路线',...CHIPS}}/><Select label="明细金额口径" value={kind} onChange={setKind} options={AMOUNTS}/><Select label="金额范围" value={amountScope} onChange={setAmountScope} options={{all:'全部范围',...SCOPES}}/><Select label="台账月份" value={month} onChange={setMonth} options={{all:'全部月份',...Object.fromEntries(months.map(m=>[m,m+(partialMonth(m,window)?'（非完整月）':'')]))}}/><label className="wide">搜索项目 / 主体<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="海光、鲲鹏、买方、项目编号…"/></label></div><div className="source-actions"><button className="button secondary" disabled={!onEdit} onClick={()=>addRow('events')}>新增台账记录</button><button className="button secondary" disabled={!onEdit} onClick={()=>addRow('leads')}>新增待核线索</button><button className="button secondary" disabled={!onEdit} onClick={()=>download(`${filePrefix}_筛选证据台账.csv`,ledgerCsv(rows),'text/csv;charset=utf-8')}><Download size={16}/>导出筛选台账</button><button className="text-button" disabled={!onEdit} onClick={()=>download(`${filePrefix}_完整研究包.json`,JSON.stringify(research,null,2),'application/json')}>下载证据与检索日志</button><button className="text-button" onClick={()=>{setCategory('all');setChip('all');setKind('award');setAmountScope('all');setMonth('all');setQuery('');setEvidenceScope('all');}}>重置筛选</button></div></section>
  <div className="stats"><div className="card stat"><span>收录独立事件</span><div className="stat-value">{count}<span>个</span></div><p>{rows.length} 条记录，其中 {rows.filter(isVerified).length} 条已核验</p></div><div className="card stat"><span>已核{AMOUNTS[kind]} · 可汇总披露额</span><div className="stat-value">{fmt(sum)}<span>万元</span></div><p>已核 {selectedAmounts.length} 项；待核披露 {fmt(reportedSum)} 万元（{selectedReported.length} 项），分列不合计</p></div><div className="card stat"><span>金额或区间披露</span><div className="stat-value">{rows.filter(e=>e.amount_cny!=null||e.amount_range_cny).length}<span>/ {rows.length} 条</span></div><p>候选、单价及不可分配框架额不汇总</p></div><div className="card stat"><span>分类月份检索执行</span><div className="stat-value">{coverage}<span>/ {Object.keys(CHILDREN).length*months.length} 格</span></div><p>{Object.keys(CHILDREN).length}个观察子项 × {months.length}个月；已执行检索不等于全量覆盖</p></div></div>
  <CategoryTrends window={window} rows={included.filter(baseMatches)} leads={pending.filter(e=>scopeMatches(e)&&baseMatches(e))} eligible={eligible} reported={reported} combined={combinedAmountRows(period).filter(baseMatches)} category={category} month={month} onSelect={selectCell} notes={research.category_notes||[]} evidence={allRecords} download={download} onEdit={onEdit}/>
  <div className="monthly-charts"><section className="card"><div className="section-heading"><div><h2>当前分类 · 收录事件与其中已核事件</h2><p>搜索样本分布；不能据此推断市场增长率</p></div></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={series}><CartesianGrid vertical={false} stroke="#edf0f5"/><XAxis dataKey="label" tick={{fontSize:12}}/><YAxis allowDecimals={false} width={32} tick={{fontSize:12}}/><Tooltip/><Legend wrapperStyle={{fontSize:12}}/><Bar dataKey="events" name="收录事件（含待核）" fill="#376fe5" radius={[3,3,0,0]}/><Bar dataKey="verified_events" name="其中已核事件" fill="#b9c0cb" radius={[3,3,0,0]}/></BarChart></ResponsiveContainer></div></section><section className="card"><div className="section-heading"><div><h2>{AMOUNTS[kind]}当月披露额 · 万元</h2><p>已核与待核分列；待核不含冲突、候选和预计区间，不能作为确定订单</p></div></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={disclosures}><CartesianGrid vertical={false} stroke="#edf0f5"/><XAxis dataKey="label" tick={{fontSize:12}}/><YAxis width={66} tick={{fontSize:12}} tickFormatter={n=>fmt(n)}/><Tooltip formatter={(v,name)=>[fmt(v)+' 万元',name]}/><Legend wrapperStyle={{fontSize:12}}/><Bar dataKey="amount" name="已核披露" fill="#2c897b" radius={[3,3,0,0]}/><Bar dataKey="reported_amount" name="待核披露" fill="#d5a44b" radius={[3,3,0,0]}/></BarChart></ResponsiveContainer></div></section></div>
  <section className="card"><h2>逐月读数</h2><div className="table-scroll"><table><thead><tr><th>月份</th><th>收录事件</th><th>买方采购 / 投产项目线索</th><th>其中待核及冲突</th><th>已核当月披露（万元）</th><th>已核当前有效额（万元）</th><th>待核披露（万元）</th><th>金额项</th><th>完整性</th></tr></thead><tbody>{series.map(r=><tr key={r.month}><td><button className="text-button" onClick={()=>setMonth(r.month)}>{r.month}</button></td><td>{r.events||'未核得'}</td><td>{r.projects||'未核得'}</td><td>{r.leads||'—'}</td><td>{fmt(disclosures.find(d=>d.month===r.month)?.amount)}</td><td>{fmt(r.amount)}</td><td>{fmt(r.reported_amount)}</td><td>{r.amount_count||'—'}</td><td>{partialMonth(r.month,window)?'非完整月；不做完整月环比':'公开样本；未建立固定分母'}</td></tr>)}</tbody></table></div><p className="footnote">待核金额仅代表公开报道中的数值，不与已核金额相加；冲突、疑似终止、候选报价、预计区间及口径不明金额只在详情展示。项目可跨月披露，项目数不能跨月相加。“—”表示没有可汇总的已核金额，并非0元。当月披露保留历史预算；当前有效额采用最新修订，疑似跨期重复项保守排除，故不同列不可相加。合同为服务全期金额，可能包含多年履约，不等于观察年度收入。金额保留公告税务口径，未统一折算含税价。项目总投资可能含土建、土地、能源和多年投入，不能视作服务器市场规模。图表保持已采集日期窗口，月份筛选作用于上方金额与下方台账。</p></section>
  <section className="card"><h2>已核样本 · 逐月判断归档</h2><p className="muted">以下保留核验口径的研究判断，不代表放宽收录后的全部样本；依据截至 {research.analysis_update?.date||research.as_of}。</p>{research.monthly_notes.map(n=><p className="month-note" key={n.month}><strong>{n.month}</strong>{n.text}{editButton('monthly_notes',n.month,n)}</p>)}</section>
  <section className="card research-judgments"><h2>已核样本 · 战略判断与下一步</h2>{(research.insights||[]).map((item,i)=><article key={i}><h3>{item.title}</h3>{editButton('insights',String(i),item)}<p><b>事实：</b>{item.fact}</p><p><b>判断：</b>{item.inference}</p><p><b>行动：</b>{item.action}</p><p className="muted">证据强度：{item.strength}　{(item.ids||[]).map(id=>{const e=allRecords.find(r=>r.id===id);return e?<a key={id} href={safeUrl(e.url)||undefined} target="_blank" rel="noreferrer">{e.customer||e.publisher} ↗　</a>:null;})}</p></article>)}</section>
  <section className="card"><div className="section-heading"><div><h2>海光与鲲鹏 · 分开看 CPU、加速卡和选择权</h2><p>点击路线查看相关项目；普通CPU采购作为补充，未强行划入国产GPU。</p></div></div><div className="chip-grid">{Object.entries(CHIPS).map(([id,name])=>{const rr=included.filter(e=>matchesChip(e,id));return <button className="chip-card" key={id} onClick={()=>{setChip(id);setAmountScope('all');setCategory('all');setMonth('all');setQuery('');}}><strong>{name}</strong><b>{new Set(rr.map(eventKey)).size} <small>事件</small></b><span>{rr.length} 条记录 · 其中 {rr.filter(isVerified).length} 条已核</span></button>;})}</div><p className="footnote">海光或鲲鹏可选的标包单列，不把全额重复分给两条路线；提及华为、GPU服务器或海光架构，不自动推定为鲲鹏、昇腾或海光DCU。同一项目可涉及多种芯片，路线筛选显示相关整包金额，路线之间不能相加。框架订单执行、验收和付费消纳需另行跟进。</p></section>
  <section className="card" id="monthly-records"><div className="section-heading"><div><h2>统一金额与事件台账</h2><p>按分类、芯片、范围、月份筛选 {rows.length} 条（台账保留所有金额性质）；展开查看原文依据与金额限制</p></div></div>{rows.length?rows.map(e=><details className="research-record" key={e.id}><summary><span><b>{e.title}</b> <span className={'badge '+researchReview(e)}>{REVIEWS[researchReview(e)]}</span><small>{e.event_date||e.published_date} · {e.customer||e.publisher} · {e.stage_label||STAGES[e.stage]||e.stage}</small></span><span className="record-money">{recordAmount(e)}<small>{researchReview(e)==='accepted'?'已核':researchReview(e)==='quarantine'?'冲突金额':'待核披露'} · {AMOUNTS[e.amount_kind]||e.amount_kind}</small></span></summary><div className="record-body"><p>{e.fact_summary}</p><p><b>观察子项：</b>{e.observation_categories.map(c=>CLASS_LABELS[c]).join(' / ')||'未命中'}{e.tags.includes('hyg_or_kunpeng')?' · 海光/鲲鹏为备选，选型未确定':''}</p><p><b>原始类别：</b>{e.categories.map(c=>TECHS[c]||c).join(' / ')||'常规芯片采购补充'}　<b>芯片：</b>{e.tags.map(t=>CHIPS[t]||t).join(' / ')||'未明示'}</p><p><b>金额原文：</b>{e.amount_text||'未披露'}　<b>范围：</b>{SCOPES[e.amount_scope]||e.amount_scope}</p><p><b>局限：</b>{e.limitations||'公开披露不代表实际付款或验收。'}</p><p><b>项目 / 标包：</b>{e.project_id||'未披露'} {e.lot||''}　<b>披露日：</b>{e.published_date}　<b>事件日：</b>{e.event_date||'未明示'}</p>{e.note&&<p><b>共享研究笔记：</b>{e.note}</p>}{editButton('events',e.id,e)}<Sources record={e}/><a href={safeUrl(e.url)||undefined} target="_blank" rel="noreferrer">核对原文 <ArrowUpRight size={14}/></a></div></details>):<div className="empty">当前筛选未收录记录；请调整筛选。</div>}</section>
  <section className="card" id="leads"><div className="section-heading"><div><h2>待核与冲突记录已纳入主台账</h2><p>当前筛选含 {leads.length} 条，可在上方台账直接查看、编辑和导出；核验用于补足证据，不再作为收录门槛。</p></div><button className="button secondary" onClick={()=>download(`${filePrefix}_筛选待核记录.csv`,ledgerCsv(leads),'text/csv;charset=utf-8')}>导出待核记录</button></div></section>
  {!!history.length&&<section className="card"><h2>窗口外或日期待定资料 · {history.length} 条</h2><p className="muted">均已保存在数据库；日期不在观察窗口或尚未明确，不强行分配月份。</p>{history.filter(matches).map(e=><details className="research-record" key={e.id}><summary>{e.published_date} · {e.title}</summary><div className="record-body"><p>{e.fact_summary}</p><p>{e.limitations}</p>{e.note&&<p>{e.note}</p>}{editButton('events',e.id,e)}<a href={safeUrl(e.url)||undefined} target="_blank" rel="noreferrer">核对原文 ↗</a></div></details>)}</section>}
  {research.audit&&<section className="card" id="reconciliation"><div className="section-heading"><div><h2>补漏与对账 · 核验口径研究归档</h2><p>{research.audit.conclusion}</p></div><a href="#leads" className="text-button">查看新闻与公众号线索 ↓</a></div><div className="stats"><div className="stat"><span>核验记录</span><div className="stat-value">{research.audit.baseline_records} → {verified.length}</div><p>归档时相对基线新增 {research.audit.added_records} 条；不代表市场增量</p></div><div className="stat"><span>补充待核线索</span><div className="stat-value">{pending.length}<span>条</span></div><p>报道、局部正文和冲突分层保留；不进核验金额</p></div><div className="stat"><span>交叉核查</span><div className="stat-value">{research.crosschecks.length}<span>组</span></div><p>包括同源追溯及冲突核对，不等于独立验证组数</p></div><div className="stat"><span>完整数据库对账</span><div className="stat-value">未完成</div><p>只报告下列限定页面或名录的对账结果</p></div></div><details className="research-record"><summary>为什么上轮只有92条，以及本次如何补漏</summary><div className="record-body">{research.audit.findings.map((f,i)=><p key={i}><b>{f.title}：</b>{f.detail}</p>)}<p>核验库、补充线索和来源篇数分别统计。同一项目多个阶段保留，转载只加来源，不新增项目。公众号身份、原文指针及可读状态随台账保存。</p></div></details>{(research.benchmarks||[]).map((b,i)=><details className="research-record" key={i}><summary>{b.title} · {b.summary}</summary><div className="record-body"><p>{b.scope}</p><p>{b.limitation}</p><div className="table-scroll"><table><thead><tr><th>条目</th><th>基线对账</th><th>处理与原因</th></tr></thead><tbody>{b.rows.map((r,j)=><tr key={j}><td><a href={safeUrl(r.url)||undefined} target="_blank" rel="noreferrer">{r.title}</a></td><td>{r.status}</td><td>{r.reason}</td></tr>)}</tbody></table></div></div></details>)}<details className="research-record"><summary>交叉验证与发现的冲突 · {research.crosschecks.length} 组</summary><div className="record-body">{research.crosschecks.map((c,i)=><article className="gap-row" key={i}><b>{c.title} · {c.result}</b><p>{c.detail}</p>{(c.sources||[]).map((s,j)=><a key={j} href={safeUrl(s.url)||undefined} target="_blank" rel="noreferrer">{s.publisher||'来源'} ↗　</a>)}</article>)}</div></details></section>}
  <section className="card"><h2>检索执行记录与其他缺口</h2><p className="muted">公开官网、采购公告与厂商原文优先；公众号和聚合站线索保留在补充库，并继续回溯原始发布。受登录、索引、反爬和未披露影响，未承诺全网穷尽。</p><details className="research-record"><summary>历史检索缺口日志（非当前待核条数） · {research.gaps.length} 项</summary>{research.gaps.map((g,i)=><p className="gap-row" key={i}>{g.url?<a href={safeUrl(g.url)||undefined} target="_blank" rel="noreferrer">{g.title||g.url}</a>:<b>{g.title||g.category||'检索缺口'}</b>}<br/>{g.reason||g.limitation||g.note||JSON.stringify(g)}</p>)}</details><details className="research-record"><summary>检索方法与统计规则</summary><div className="record-body"><p>按“分类同义词 × 月份 × 采购/中标/合同/投产”等检索，再追加买方、厂商和站点限定；对命中项核验正文日期、项目编号、买方和金额性质。检索日志随研究包导出。</p><p>同一项目不同采购阶段保留；同一事件转载归并；标包拆开存金额。相同项目/标包/金额类型保留最新有效披露。候选报价、单位价格、未分配的多家框架金额不纳入汇总，未披露用空值。</p><p>算力场采用已确认的扩展定义：算力资源池、统一调度、算力网/算力互联网，以及AI一体机采购与部署；不含只有机房建设的项目。旧分类已合并，分类口径变化不能解读为市场增长。光交换机严格区分OCS与普通以太网交换机；EDA包含设计工具、仿真与算力基础设施；软件许可不计作服务器硬件。</p><p>新闻、公众号和公开索引可先行入库，默认进入信息量统计；核验状态独立保留。已核与待核披露金额分列，冲突和估算不进入确定金额。</p><p>本页为共享研究台账，所有访客均可编辑记录和研究判断。保存后图表与导出使用最新共享数据；多人同时修改同一条目时会提示版本冲突。各栏目使用同一份台账，采集与导入的新线索也同步显示。未建立固定来源分母，不输出市场份额、完整月增长率或综合热度排名。</p></div></details></section>
 </div>;
}
