'use client';
import {useState,useMemo} from 'react';
import TrendBarChart from './trend-bar-chart';
import {Download,ArrowUpRight} from 'lucide-react';

import CategoryTrends from './category-trends';
import {TECHS,STAGES,SCOPES,REVIEWS,safeUrl,researchReview,dateWindow,monthsInWindow,partialMonth} from '@/lib/model';
import {AMOUNTS,CHIPS,inObservationPeriod,inResearchPeriod,amountRows,reportedAmountRows,combinedAmountRows,monthlyDisclosureRows,monthlySeries,eventKey,monthOf,ledgerCsv} from '@/lib/monthly';
import {CHILDREN,CLASS_LABELS,matchesCategory,matchesChip,observationCategories} from '@/lib/hierarchy';
const fmt=n=>n==null?'—':n.toLocaleString('zh-CN',{maximumFractionDigits:2});
const recordAmount=e=>e.amount_range_cny?`${fmt(e.amount_range_cny.min/1e8)}—${fmt(e.amount_range_cny.max/1e8)} 亿元（预计）`:e.amount_cny==null?'金额未披露 / 待核':`¥${fmt(e.amount_cny)}`;
function download(name,content,type){const u=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function Select({label,value,onChange,options}){return <label>{label}<select aria-label={label} value={value} onChange={e=>onChange(e.target.value)}>{Object.entries(options).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>;}
function Sources({record:e}){return <><p><b>核查状态：</b>{e.evidence_status==='primary'?'原始披露正文已读':e.evidence_status==='reported'?'报道正文已读，待原始披露确认':e.evidence_status==='conflict'?'存在冲突，金额隔离':e.evidence_status==='lead'?(e.verified_fulltext?'正文已读，其他核查条件未满足':'索引 / 局部线索，待核原文'):'正文已读（保留发布者角色）'}　{e.source_read_result}</p>{e.service_duration_months&&<p><b>服务期：</b>{e.service_duration_months} 个月　{e.service_start_basis}　{e.payment_terms}</p>}{e.tag_qualifiers&&<p><b>选型限制：</b>{Object.values(e.tag_qualifiers).join('；')}</p>}{e.wechat_account&&<p><b>公众号：</b>{e.wechat_account}</p>}{(e.corroborating_sources||[]).map((s,i)=><p key={i}><a href={safeUrl(s.url)||undefined} target="_blank" rel="noreferrer">{s.publisher||s.title||'关联来源'} ↗</a>　{s.relationship} · {s.read_status}{s.independent===false?' · 同源，不算独立验证':''}</p>)}{e.lineage&&<p className="footnote">来源链：{e.lineage}</p>}</>;}
export default function MonthlyResearch({research,onEdit}){
 const [category,setCategory]=useState('all'),[chip,setChip]=useState('all'),[kind,setKind]=useState('award'),[month,setMonth]=useState('all'),[query,setQuery]=useState(''),[amountScope,setAmountScope]=useState('all'),[evidenceScope,setEvidenceScope]=useState('all');
 const window=dateWindow(research),months=monthsInWindow(window),isObserved=e=>inObservationPeriod(e,window),isVerified=e=>inResearchPeriod(e,window),rangeLabel=`${window.start} 至 ${window.end}`,filePrefix=`${window.start}_${window.end}`;
 const allRecords=useMemo(()=>[...research.events.map(e=>({...e,_section:'events'})),...research.leads.map(e=>({...e,_section:'leads'}))].map(e=>({...e,observation_categories:observationCategories(e)})),[research]);
 const period=allRecords.filter(isObserved),verified=period.filter(isVerified),pending=period.filter(e=>researchReview(e)!=='accepted'),history=allRecords.filter(e=>!isObserved(e));
 const scopeMatches=e=>evidenceScope==='all'||(evidenceScope==='pending'?researchReview(e)!=='accepted':researchReview(e)===evidenceScope),included=period.filter(scopeMatches);
 const editButton=(section,key,e)=><button className="text-button" disabled={!onEdit} onClick={()=>onEdit(e._section||section,key,e)}>编辑{section==='events'?'台账':section==='leads'?'线索':'判断'}</button>;
 function addRow(section){const id=crypto.randomUUID();onEdit(section,id,{id,title:'',url:'',publisher:'',customer:'',project_id:id,event_key:id,published_date:'',event_date:null,stage:'research',source_type:'unknown',categories:[],tags:[],amount_cny:null,amount_kind:'none',amount_scope:'unknown',amount_text:'',fact_summary:'',limitations:'',verified_fulltext:false,amount_eligible:false,evidence_status:section==='events'?'primary':'lead',_revision:0});}
 const baseMatches=e=>(amountScope==='all'||e.amount_scope===amountScope)&&matchesChip(e,chip)&&(!query||[e.title,e.customer,e.publisher,e.fact_summary,e.project_id,e.wechat_account].join(' ').toLowerCase().includes(query.toLowerCase()));
 const matches=e=>baseMatches(e)&&matchesCategory(e,category);
 const matching=included.filter(matches),matchingLeads=matching.filter(e=>researchReview(e)!=='accepted'),leads=matchingLeads.filter(e=>month==='all'||monthOf(e)===month);
 const eligible=amountRows(period),reported=reportedAmountRows(period),reportedSeries=monthlySeries(matching,kind,reported,window),verifiedSeries=monthlySeries(matching.filter(isVerified),kind,eligible,window);
 const series=monthlySeries(matching,kind,eligible,window).map((s,i)=>({...s,verified_events:verifiedSeries[i].events,leads:matchingLeads.filter(e=>monthOf(e)===s.month).length,reported_amount:reportedSeries[i].amount})),disclosures=monthlySeries(matching,kind,monthlyDisclosureRows(verified,window),window).map((s,i)=>({...s,reported_amount:reportedSeries[i].amount})),rows=matching.filter(e=>month==='all'||monthOf(e)===month).sort((a,b)=>(b.event_date||b.published_date).localeCompare(a.event_date||a.published_date));
 function selectCell(c,m,metric){setCategory(c);setMonth(m);if(metric==='total_amount')setEvidenceScope('all');}
 const selectedAmounts=eligible.filter(e=>rows.some(r=>r.id===e.id)&&e.amount_kind===kind),sum=selectedAmounts.length?selectedAmounts.reduce((s,e)=>s+e.amount_cny,0)/1e4:null;
 const selectedReported=reported.filter(e=>rows.some(r=>r.id===e.id)&&e.amount_kind===kind),reportedSum=selectedReported.length?selectedReported.reduce((s,e)=>s+e.amount_cny,0)/1e4:null;
 const count=new Set(rows.map(eventKey)).size,coverage=new Set(research.queries.filter(q=>CHILDREN[q.category]&&months.includes(q.month)).map(q=>q.category+'|'+q.month)).size;
 return <div className="monthly-research">
  <div className="notice"><strong>{rangeLabel} · 收录 {period.length} 条 · 已核 {verified.length} 条 · 待核及冲突 {pending.length} 条 · 窗口外或日期待定 {history.length} 条</strong></div>
  <section className="card monthly-controls"><div className="source-filters"><Select label="证据范围" value={evidenceScope} onChange={setEvidenceScope} options={{all:'全部收录（含待核）',accepted:'仅已核验',pending:'待核与冲突',quarantine:'仅冲突记录'}}/><Select label="项目分类" value={category} onChange={setCategory} options={{all:'全部（含芯片采购补充）',...CLASS_LABELS}}/><Select label="芯片路线" value={chip} onChange={setChip} options={{all:'全部路线',...CHIPS}}/><Select label="明细金额口径" value={kind} onChange={setKind} options={AMOUNTS}/><Select label="金额范围" value={amountScope} onChange={setAmountScope} options={{all:'全部范围',...SCOPES}}/><Select label="台账月份" value={month} onChange={setMonth} options={{all:'全部月份',...Object.fromEntries(months.map(m=>[m,m+(partialMonth(m,window)?'（非完整月）':'')]))}}/><label className="wide">搜索项目 / 主体<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="海光、鲲鹏、买方、项目编号…"/></label></div><div className="source-actions"><button className="button secondary" disabled={!onEdit} onClick={()=>addRow('events')}>新增台账记录</button><button className="button secondary" disabled={!onEdit} onClick={()=>addRow('leads')}>新增待核线索</button><button className="button secondary" disabled={!onEdit} onClick={()=>download(`${filePrefix}_筛选证据台账.csv`,ledgerCsv(rows),'text/csv;charset=utf-8')}><Download size={16}/>导出筛选台账</button><button className="text-button" disabled={!onEdit} onClick={()=>download(`${filePrefix}_完整研究包.json`,JSON.stringify(research,null,2),'application/json')}>下载证据与检索日志</button><button className="text-button" onClick={()=>{setCategory('all');setChip('all');setKind('award');setAmountScope('all');setMonth('all');setQuery('');setEvidenceScope('all');}}>重置筛选</button></div></section>
  <div className="stats"><div className="card stat"><span>收录独立事件</span><div className="stat-value">{count}<span>个</span></div><p>{rows.length} 条记录，其中 {rows.filter(isVerified).length} 条已核验</p></div><div className="card stat"><span>已核{AMOUNTS[kind]} · 可汇总披露额</span><div className="stat-value">{fmt(sum)}<span>万元</span></div><p>已核 {selectedAmounts.length} 项 · 待核 {fmt(reportedSum)} 万元 / {selectedReported.length} 项</p></div><div className="card stat"><span>金额或区间披露</span><div className="stat-value">{rows.filter(e=>e.amount_cny!=null||e.amount_range_cny).length}<span>/ {rows.length} 条</span></div></div><div className="card stat"><span>分类月份检索执行</span><div className="stat-value">{coverage}<span>/ {Object.keys(CHILDREN).length*months.length} 格</span></div><p>{Object.keys(CHILDREN).length} 个子项 × {months.length} 个月</p></div></div>
  <CategoryTrends window={window} rows={included.filter(baseMatches)} leads={pending.filter(e=>scopeMatches(e)&&baseMatches(e))} eligible={eligible} reported={reported} combined={combinedAmountRows(period).filter(baseMatches)} category={category} month={month} onSelect={selectCell} download={download} onEdit={onEdit}/>
  <div className="monthly-charts"><section className="card"><div className="section-heading"><div><h2>收录与已核事件</h2></div></div><TrendBarChart data={series} yAxis={{allowDecimals:false}} bars={[{dataKey:'events',name:'收录事件（含待核）',fill:'#376fe5'},{dataKey:'verified_events',name:'其中已核事件',fill:'#b9c0cb'}]}/></section><section className="card"><div className="section-heading"><div><h2>{AMOUNTS[kind]}当月披露额 · 万元</h2></div></div><TrendBarChart data={disclosures} yAxis={{tickFormatter:n=>fmt(n)}} tooltip={{formatter:(v,name)=>[fmt(v)+' 万元',name]}} bars={[{dataKey:'amount',name:'已核披露',fill:'#2c897b'},{dataKey:'reported_amount',name:'待核披露',fill:'#d5a44b'}]}/></section></div>
  <section className="card"><h2>逐月读数</h2><div className="table-scroll"><table><thead><tr><th>月份</th><th>收录事件</th><th>买方采购 / 投产项目线索</th><th>其中待核及冲突</th><th>已核当月披露（万元）</th><th>已核当前有效额（万元）</th><th>待核披露（万元）</th><th>金额项</th><th>完整性</th></tr></thead><tbody>{series.map(r=><tr key={r.month}><td><button className="text-button" onClick={()=>setMonth(r.month)}>{r.month}</button></td><td>{r.events||'未核得'}</td><td>{r.projects||'未核得'}</td><td>{r.leads||'—'}</td><td>{fmt(disclosures.find(d=>d.month===r.month)?.amount)}</td><td>{fmt(r.amount)}</td><td>{fmt(r.reported_amount)}</td><td>{r.amount_count||'—'}</td><td>{partialMonth(r.month,window)?'非完整月':'公开样本'}</td></tr>)}</tbody></table></div></section>
  <section className="card"><div className="section-heading"><div><h2>芯片路线</h2><p>点击筛选项目</p></div></div><div className="chip-grid">{Object.entries(CHIPS).map(([id,name])=>{const rr=included.filter(e=>matchesChip(e,id));return <button className="chip-card" key={id} onClick={()=>{setChip(id);setAmountScope('all');setCategory('all');setMonth('all');setQuery('');}}><strong>{name}</strong><b>{new Set(rr.map(eventKey)).size} <small>事件</small></b><span>{rr.length} 条记录 · 其中 {rr.filter(isVerified).length} 条已核</span></button>;})}</div></section>
  <section className="card" id="monthly-records"><div className="section-heading"><div><h2>统一金额与事件台账</h2><p>{rows.length} 条 · 展开查看详情</p></div></div>{rows.length?rows.map(e=><details className="research-record" key={e.id}><summary><span><b>{e.title}</b> <span className={'badge '+researchReview(e)}>{REVIEWS[researchReview(e)]}</span><small>{e.event_date||e.published_date} · {e.customer||e.publisher} · {e.stage_label||STAGES[e.stage]||e.stage}</small></span><span className="record-money">{recordAmount(e)}<small>{researchReview(e)==='accepted'?'已核':researchReview(e)==='quarantine'?'冲突金额':'待核披露'} · {AMOUNTS[e.amount_kind]||e.amount_kind}</small></span></summary><div className="record-body"><p>{e.fact_summary}</p><p><b>观察子项：</b>{e.observation_categories.map(c=>CLASS_LABELS[c]).join(' / ')||'未命中'}{e.tags.includes('hyg_or_kunpeng')?' · 海光/鲲鹏为备选，选型未确定':''}</p><p><b>原始类别：</b>{e.categories.map(c=>TECHS[c]||c).join(' / ')||'常规芯片采购补充'}　<b>芯片：</b>{e.tags.map(t=>CHIPS[t]||t).join(' / ')||'未明示'}</p><p><b>金额原文：</b>{e.amount_text||'未披露'}　<b>范围：</b>{SCOPES[e.amount_scope]||e.amount_scope}</p><p><b>局限：</b>{e.limitations||'公开披露不代表实际付款或验收。'}</p><p><b>项目 / 标包：</b>{e.project_id||'未披露'} {e.lot||''}　<b>披露日：</b>{e.published_date}　<b>事件日：</b>{e.event_date||'未明示'}</p>{e.note&&<p><b>共享研究笔记：</b>{e.note}</p>}{editButton('events',e.id,e)}<Sources record={e}/><a href={safeUrl(e.url)||undefined} target="_blank" rel="noreferrer">核对原文 <ArrowUpRight size={14}/></a></div></details>):<div className="empty">当前筛选未收录记录；请调整筛选。</div>}</section>
  <section className="card" id="leads"><div className="section-heading"><div><h2>待核与冲突</h2><p>{leads.length} 条</p></div><button className="button secondary" onClick={()=>download(`${filePrefix}_筛选待核记录.csv`,ledgerCsv(leads),'text/csv;charset=utf-8')}>导出待核记录</button></div></section>
  {!!history.length&&<section className="card"><h2>窗口外或日期待定资料 · {history.length} 条</h2>{history.filter(matches).map(e=><details className="research-record" key={e.id}><summary>{e.published_date} · {e.title}</summary><div className="record-body"><p>{e.fact_summary}</p><p>{e.limitations}</p>{e.note&&<p>{e.note}</p>}{editButton('events',e.id,e)}<a href={safeUrl(e.url)||undefined} target="_blank" rel="noreferrer">核对原文 ↗</a></div></details>)}</section>}
 </div>;
}
