'use client';
import {useEffect,useState} from 'react';
import {safeUrl} from '@/lib/model';
import {CLASS_LABELS} from '@/lib/hierarchy';
import {sourcePanel} from '@/data/sources';
import rolling from '@/data/rolling-update.json';
import remediation from '@/data/source-remediation.json';

const when=value=>value?new Date(value).toLocaleString('zh-CN'):'—';
const sourceName=id=>sourcePanel.find(s=>s.id===id)?.name||id;
const captureLabels={fetched:'已提取',discovered:'栏目已读取',failed:'读取失败',pdf:'PDF 待导入',imported:'已导入'};
function Fold({title,children}){return <details className="card log-section"><summary>{title}</summary><div className="log-body">{children}</div></details>;}
function Link({url,children}){return safeUrl(url)?<a href={safeUrl(url)} target="_blank" rel="noreferrer">{children} ↗</a>:<span>{children}</span>;}
function download(name,value){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

export default function ResearchLog({data,research,monitoring,onEdit,method}){
 const [tab,setTab]=useState('updates'),[samples,setSamples]=useState(null),[sampleError,setSampleError]=useState('');
 useEffect(()=>{let active=true;fetch('/sample-sources.json').then(r=>{if(!r.ok)throw Error('来源覆盖日志暂时无法读取');return r.json();}).then(d=>{if(active)setSamples(d);}).catch(e=>{if(active)setSampleError(e.message);});return()=>{active=false;};},[]);
 const records=[...research.events,...research.leads],captures=data?.captures||[],queries=research.queries||[];
 const edit=(section,key,record)=><button className="text-button" disabled={!onEdit} onClick={()=>onEdit(section,key,record)}>编辑判断</button>;
 const references=ids=>(ids||[]).map(id=>records.find(r=>r.id===id)).filter(Boolean).map(r=><p key={r.id}><Link url={r.url}>{r.title}</Link></p>);
 return <div className="research-log">
  <div className="pills" role="group" aria-label="日志类型">{Object.entries({updates:'更新记录',method:'统计说明',research:'研究归档',collection:'采集记录'}).map(([id,label])=><button key={id} aria-pressed={tab===id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div>
  {tab==='updates'&&<>
   <section className="card"><h2>最近更新</h2><p>完整更新截至 {monitoring.last_completed_cutoff||'—'} · {monitoring.schedule_label||'按需更新'}</p>{monitoring.latest_requested_cutoff&&<p>最近尝试至 {monitoring.latest_requested_cutoff} · {monitoring.latest_update_status==='partial'?'部分完成':'已完成'}</p>}<p>{monitoring.latest_status}</p>{monitoring.last_attempt_at&&<p>尝试时间：{when(monitoring.last_attempt_at)}</p>}<details><summary>更新与异动规则</summary><p>{monitoring.execution}</p><p>{monitoring.rule_summary}</p><p>监测窗口：{monitoring.latest_window?.start||rolling.monitoring.window.start} 至 {monitoring.latest_window?.end||rolling.monitoring.window.end}</p><p>每轮全量回查；通过检查的来源月份独立写入，失败月份保留原资料并标明实际截止。固定来源不因采集失败而从分母中剔除；受影响月份暂停比例比较。</p></details></section>
   <Fold title={`异动记录 · ${(monitoring.latest_alerts||[]).length} 条`}>{(monitoring.latest_alerts||[]).map((a,i)=><article className="gap-row" key={a.id||i}><h3>{a.title}</h3><p>{a.detail||a.reason}</p>{a.url&&<Link url={a.url}>原文</Link>}{(a.urls||[]).map(url=><p key={url}><Link url={url}>{url}</Link></p>)}</article>)}</Fold>
   <Fold title="界面调整 · 2026-09-24"><p>月度热力表点击后保留筛选，取消自动跳转。页面长说明、复核与采集归档集中至日志；统计口径和原始数据未修改。</p></Fold>
   <Fold title={`研究补采归档 · ${rolling.checked_at.slice(0,10)}`}><p>{rolling.summary}</p><p>补采增加历史收录量，不代表同期市场增长。入口检查与全量采集分别记录。</p><a href="/rolling-update.json" download>下载补采记录</a><p><a href="/rolling-preview-news.json" download>下载窗口外新闻预览</a></p>{(rolling.insights||[]).map(i=><article key={i.title}><h3>{i.title}</h3><p>{i.text}</p><Link url={i.url}>依据</Link></article>)}<details><summary>原文来源 · {rolling.backfill_sources.length} 个</summary>{rolling.backfill_sources.map(s=><p key={s.host}><Link url={s.url}>{s.publisher}</Link> · {s.records} 条</p>)}</details><details><summary>窗口外线索 · {rolling.preview.length} 条</summary><p>未计入截至 {rolling.cutoff} 的完整周图表；原文可读不等于实际采购。</p>{rolling.preview.map((r,i)=><p key={i}>{r.published_date||r.date} · <Link url={r.url}>{r.title}</Link> · {r.result||r.status}</p>)}</details></Fold>
   {research.expansion&&<Fold title={`扩样归档 · ${research.expansion.retrieved_on}`}><p>{research.expansion.summary}</p><p>{research.expansion.limitations}</p>{(research.expansion.sources||[]).map((s,i)=><p key={i}><Link url={s.url}>{s.name||s.host}</Link> · {s.records} 条 · {s.method}</p>)}</Fold>}
  </>}
  {tab==='method'&&<>
   <Fold title="市场风向与分类口径">{method}</Fold>
   <Fold title="月度事件与金额口径"><p>事件日优先，未披露时使用发布日期。待核、已核与冲突状态随记录保留；未取得资料不等于没有需求。</p><p>金额热力表合并预算、成交、合同、投资、报价和预估披露；同一项目或标包采用最新披露一次，同日优先合同与成交。区间保留上下限并按下限着色；单位价格、无金额、失效及冲突项不计。类别可重叠，不跨行相加。</p><p>金额总图不受“证据范围”和“明细金额口径”筛选影响；芯片、金额范围和搜索仍适用。其他金额明细保留已核与待核、金额类型的区别。已核与待核列不相加；当月披露保留历史预算，当前有效额按最新修订并排除疑似跨期重复，两列不能相加。芯片筛选显示相关整包金额，不能跨路线相加；原始公告税务口径保留，未统一折算含税价。总投资可能包含土建、能源等，合同可能跨年，披露额不等于服务器销售额、实际支付或市场规模。</p><p>图表中的“—”为缺口或无可汇总金额，不能解释为零；“*”为非完整时期。样本量、颜色和标题提及不能单独证明采用率或市场增长。</p><details><summary>历史研究方法</summary>{Object.entries(research.methodology||{}).map(([key,value])=><p key={key}>{value}</p>)}</details></Fold>
   <Fold title="采集与导入说明"><p>记录和研究判断可在台账中编辑。保存后图表与导出采用当前数据；同一记录的版本冲突会提示重新加载，已有笔记保留。</p><p>公开栏目检查只读取当前入口；定向检索和单条导入进入研究台账，不改变市场风向的固定新闻分母。公众号仅尝试读取已知文章链接，访问限制与授权状态保留。</p><p>支持 CSV、JSON、TXT、PDF。标题和 HTTPS 原文链接必填，每批最多50条；日期未知留空。金额需填写类型及单位，预计区间通过 JSON 的 amount_range_cny 导入，单位为人民币元。</p><p>相同原文、明确项目编号和标包用于识别重复；不同标包分行，不覆盖已有笔记。新记录保留待核状态。商业 API 未授权时使用公开资料或有权导出的文件，不代表全库接通。</p></Fold>
   <Fold title="逐源覆盖与限制">{sampleError&&<p role="alert">{sampleError}</p>}{!samples&&!sampleError&&<p>正在读取…</p>}{(samples?.sources||[]).map(s=><details className="research-record" key={s.id}><summary>{s.name}</summary><div className="record-body"><p>{s.scope}</p><p>{s.method}</p><p>{s.limitation}</p><Link url={s.url}>来源入口</Link>{(s.coverage||[]).map(c=><p key={c.month}>{c.month} · {c.status==='complete'?'覆盖已核对':c.status==='stale'?'沿用旧资料':c.status==='missing'?'缺口':'覆盖不完整'}{c.covered_through&&` · 截至 ${c.covered_through}`} · {c.reason||c.note}</p>)}</div></details>)}{(samples?.unavailable_sources||[]).map(s=><p key={s.name}>{s.name}：{s.reason}</p>)}<a href="/sample-sources.json" download>下载来源覆盖记录</a></Fold>
  </>}
  {tab==='research'&&<>
   <Fold title="战略判断归档">{(research.insights||[]).map((n,i)=><article className="gap-row" key={i}><h3>{n.title}</h3>{edit('insights',String(i),n)}<p><b>事实：</b>{n.fact}</p><p><b>判断：</b>{n.inference}</p><p><b>行动：</b>{n.action}</p><p>证据强度：{n.strength}</p>{references(n.ids)}</article>)}</Fold>
   <Fold title="逐月判断归档">{(research.monthly_notes||[]).map(n=><article className="gap-row" key={n.month}><h3>{n.month}</h3>{edit('monthly_notes',n.month,n)}<p>{n.text}</p></article>)}</Fold>
   <Fold title="分类判断归档">{(research.category_notes||[]).map(n=><article className="gap-row" key={n.category}><h3>{CLASS_LABELS[n.category]||n.category} · {n.trend}</h3>{edit('category_notes',n.category,n)}<p><b>事实：</b>{n.findings}</p><p><b>判断：</b>{n.interpretation}</p><p><b>行动：</b>{n.action}</p><p>{n.limitations}</p>{references(n.record_ids)}</article>)}</Fold>
   {research.recheck&&<Fold title={`逐条复核 · ${research.recheck.checked_at} · ${research.recheck.entries.length} 条`}><p>{research.recheck.scope}</p><button className="text-button" onClick={()=>download(`${research.recheck.checked_at}_复核记录.json`,research.recheck)}>导出复核记录</button>{research.recheck.entries.map(e=><details className="research-record" key={e.id}><summary>{e.title} · {{promote:'转入核验',retain:'继续待核',exclude:'范围外保留'}[e.decision]}</summary><div className="record-body"><p>{e.reason}</p>{e.unresolved?.length>0&&<p>未解决：{e.unresolved.join('；')}</p>}<p>下一步：{e.next_action}</p>{(e.sources||[]).map((s,i)=><p key={i}><Link url={s.url}>{s.publisher||'核查来源'}</Link> · {{fulltext:'正文已读',snippet:'仅索引/摘要',unavailable:'无法读取'}[s.read_status]||s.read_status} · {s.finding}</p>)}</div></details>)}</Fold>}
   <Fold title="补漏与数据库对账"><p>{research.audit?.conclusion}</p>{(research.audit?.findings||[]).map((f,i)=><p key={i}><b>{f.title}：</b>{f.detail}</p>)}{(research.benchmarks||[]).map((b,i)=><details className="research-record" key={i}><summary>{b.title||b.database}</summary><div className="record-body"><p>{b.summary}</p><p>{b.scope||b.population}</p><p>{b.limitation||b.rate_warning}</p><div className="table-scroll"><table><thead><tr><th>条目</th><th>对账</th><th>处理与原因</th></tr></thead><tbody>{(b.rows||[]).map((r,j)=><tr key={j}><td><Link url={r.url}>{r.title}</Link></td><td>{r.status}</td><td>{r.reason}</td></tr>)}</tbody></table></div></div></details>)}</Fold>
   <Fold title={`交叉验证 · ${(research.crosschecks||[]).length} 组`}>{(research.crosschecks||[]).map((c,i)=><article className="gap-row" key={i}><h3>{c.title} · {c.result}</h3><p>{c.detail}</p>{(c.sources||[]).map((s,j)=><p key={j}><Link url={s.url}>{s.publisher||'来源'}</Link></p>)}</article>)}</Fold>
  </>}
  {tab==='collection'&&<>
   <Fold title="来源入口与查询限制">{sourcePanel.map(s=><details className="research-record" key={s.id}><summary>{s.name}</summary><p>{s.note}</p><Link url={s.url}>来源入口</Link></details>)}</Fold>
   <Fold title={`最近栏目检查 · ${Object.keys(data?.sourceChecks||{}).length} 个来源`}>{Object.entries(data?.sourceChecks||{}).map(([id,c])=><article className="gap-row" key={id}><h3>{sourceName(id)} · {captureLabels[c.status]||c.status}</h3><p>{when(c.captured_at)} · {c.message}</p><Link url={c.url}>检查页面</Link></article>)}</Fold>
   <Fold title={`读取与导入 · ${captures.length} 条`}>{captures.map(c=><div className="capture-row" key={c.id}><span className="badge">{captureLabels[c.status]||c.status}</span><div><Link url={c.url}>{c.title||c.url}</Link><small>{c.message}</small></div><time>{when(c.captured_at)}</time></div>)}{!captures.length&&<p>{data?'暂无读取记录':'尚未连接台账，当前仅展示研究归档。'}</p>}</Fold>
   <Fold title={`月度检索 · ${queries.length} 条`}>{queries.map((q,i)=><div className="capture-row" key={i}><span>{q.month}</span><div><strong>{CLASS_LABELS[q.category]||q.category} · {q.query}</strong><small>{q.result_summary||q.note}</small></div></div>)}</Fold>
   {[{date:rolling.checked_at,rows:rolling.sources},{date:remediation.checked_at,rows:remediation.sources}].map((batch,i)=><Fold key={i} title={`来源检查归档 · ${batch.date.slice(0,10)} · ${batch.rows.length} 个入口`}>{batch.rows.map(s=><details className="research-record" key={s.source_id}><summary>{s.name||sourceName(s.source_id)} · {s.label}</summary><div className="record-body"><p>{s.result}</p><p>{s.coverage}</p><p>{typeof s.coverage_detail==='string'?s.coverage_detail:s.coverage_detail?.scope}</p>{s.assistance&&<><p><b>待协助：</b>{s.assistance.task}</p><p>{s.assistance.query}</p><Link url={s.assistance.url}>查询入口</Link></>}{(s.public_urls||[]).map((url,j)=><p key={j}><Link url={typeof url==='string'?url:url.url}>{typeof url==='string'?url:url.title||url.url}</Link></p>)}</div></details>)}</Fold>)}
   <Fold title={`历史检索缺口 · ${(research.gaps||[]).length} 项`}>{(research.gaps||[]).map((g,i)=><article className="gap-row" key={i}><Link url={g.url}>{g.title||g.topic||g.category||'检索缺口'}</Link><p>{typeof g==='string'?g:g.reason||g.limitation||g.note||g.issue||g.detail||g.description}</p></article>)}</Fold>
   <a href="/source-remediation.json" download>下载来源补采与协助清单</a>
  </>}
 </div>;
}
