'use client';
import {useEffect,useState,useRef} from 'react';
import {Search,ArrowUpRight,Upload,RefreshCw,CheckCircle2,ChevronRight} from 'lucide-react';
import {TECHS,STAGES,SOURCES,SCOPES,REVIEWS,safeUrl,monthsInWindow,monthLabel} from '@/lib/model';
import {AMOUNTS} from '@/lib/monthly';
import {sourcePanel,CATEGORIES} from '@/data/sources';
import {parseImport} from '@/lib/imports';
import taxonomy from '@/data/taxonomy.json';
import remediation from '@/data/source-remediation.json';
import rolling from '@/data/rolling-update.json';

async function request(body){const r=await fetch('/api/radar',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error||'操作暂未完成');return d;}
const labels={fetched:'已提取 · 待核验',discovered:'栏目已读取',failed:'需手动处理',pdf:'PDF 待导入',imported:'已导入 · 待核验',reading:'读取中'};
const modeLabel={public:'按需读取',manual:'官方查询 / 导入',license:'文件导入 · API 未授权'};
const when=value=>value?new Date(value).toLocaleString('zh-CN'):'';
const coverageLabel=c=>c.status==='complete'?`覆盖已核对${c.covered_through?' · 截至'+c.covered_through:''}`:c.status==='stale'?`沿用旧数据 · ${c.covered_through?'截至'+c.covered_through:'截止未确认'}`:c.status==='missing'?'未取得完整数据':'覆盖不完整';
export default function SourceCenter({data,refresh,inspect,create}){
 const [samples,setSamples]=useState(null),[sampleError,setSampleError]=useState('');
 useEffect(()=>{let active=true;fetch('/sample-sources.json').then(r=>{if(!r.ok)throw Error('固定样本采集记录暂时无法读取');return r.json();}).then(d=>{if(active)setSamples(d);}).catch(e=>{if(active)setSampleError(e.message);});return()=>{active=false;};},[]);
 const [category,setCategory]=useState('all'),[selected,setSelected]=useState('h3c'),[tech,setTech]=useState('liquid_cooling'),[keyword,setKeyword]=useState('液冷 冷板 浸没式 CDU 服务器 智算'),[url,setUrl]=useState(''),[busy,setBusy]=useState(''),[notice,setNotice]=useState(''),[error,setError]=useState(''),[result,setResult]=useState(null),[progress,setProgress]=useState('');
 const [draft,setDraft]=useState({title:'',url:'',excerpt:'',published_date:''}),[preview,setPreview]=useState([]),[fileLabel,setFileLabel]=useState('');
 const cancelled=useRef(false),source=sourcePanel.find(s=>s.id===selected),shown=sourcePanel.filter(s=>category==='all'||s.category===category),checks=data.sourceChecks||{};
 const currentCheck=result?.capture?.kind==='discover'&&result.capture.source_id===selected?result.capture:checks[selected];
 const terms=taxonomy.technologies.find(t=>t.id===tech)?.include||[];
 const followup=rolling.sources.find(s=>s.source_id===selected)||remediation.sources.find(s=>s.source_id===selected);
 const query=`site:${source.hosts[0]} (${terms.map(t=>'"'+t+'"').join(' OR ')}) (采购 OR 中标 OR 验收 OR 上线 OR 扩容 OR 取消 OR 发布)`;
 function changeTech(value){setTech(value);setKeyword([...(taxonomy.technologies.find(t=>t.id===value)?.include||[]),'服务器','智算'].join(' '));}
 async function discover(s){return request({op:'discover',source_id:s.id,keyword,tech});}
 async function check(one){
  setBusy('check');setError('');setNotice('');cancelled.current=false;
  const list=one?[one]:shown.filter(s=>s.mode==='public');let done=0,ok=0;
  try{for(let i=0;i<list.length;i+=2){if(cancelled.current)break;const batch=await Promise.allSettled(list.slice(i,i+2).map(discover));for(const r of batch){done++;if(r.status==='fulfilled'){if(r.value.capture.status==='discovered')ok++;if(one)setResult(r.value);}else setError(r.reason.message);}setProgress(`已检查 ${done}/${list.length} 个来源，${ok} 个栏目可读`);await refresh();}
   setNotice(`${cancelled.current?'已停止，':''}完成 ${done} 个来源检查，${ok} 个栏目可读。结果已保存；未读取或无命中不能视为无需求。`);
  }catch(e){setError(e.message);}finally{setBusy('');setProgress('');}
 }
 async function collect(target=url,title=''){
  setBusy('collect');setError('');setNotice('');setResult(null);
  try{const r=await request({op:'collect',url:target,tech});setResult(r);
   if(r.capture.status==='pdf'){const {pdfText}=await import('@/lib/pdf-text');const bytes=Uint8Array.from(atob(r.capture.pdf_base64),c=>c.charCodeAt(0));const text=await pdfText(bytes);setDraft({title:title||'请填写 PDF 公告标题',url:r.capture.url,excerpt:text.excerpt,published_date:''});setPreview([]);setNotice('PDF 正文已放入下方导入区，请确认标题、原文链接，再预览导入。');setResult({capture:{...r.capture,pdf_base64:undefined}});}
   await refresh();
  }catch(e){setError(e.message);}finally{setBusy('');}
 }
 async function fileChanged(file){
  if(!file)return;setBusy('file');setError('');setNotice('');setPreview([]);setFileLabel(file.name);
  try{
   if(/\.pdf$/i.test(file.name)){if(file.size>5000000)throw Error('PDF 最多5 MB。');const {pdfText}=await import('@/lib/pdf-text');const r=await pdfText(new Uint8Array(await file.arrayBuffer()));setDraft({title:file.name.replace(/\.pdf$/i,''),url:'',published_date:'',excerpt:r.excerpt});setNotice('PDF 已在浏览器提取文本。补充原文链接后预览导入；不保存 PDF 原件。');}
   else{if(file.size>800000)throw Error('文件最多800 KB。');const text=await file.text();if(/\.(csv|json)$/i.test(file.name)){setPreview(parseImport(text,file.name));setNotice('已解析文件，请核对下方预览后导入。');}else if(/\.txt$/i.test(file.name)){if(text.length>16000)throw Error('TXT 正文最多16,000字，请截取相关部分。');setDraft({title:file.name.replace(/\.txt$/i,''),url:'',published_date:'',excerpt:text});setNotice('请补充标题与原文链接，再预览导入。');}else throw Error('支持 CSV、JSON、TXT 和 PDF。');}
  }catch(e){setError(e.message);}finally{setBusy('');}
 }
 function previewText(){try{setPreview(parseImport(JSON.stringify([draft]),'manual.json'));setError('');}catch(e){setError(e.message);}}
 function assist(id){setSelected(id);setCategory('all');setResult(null);document.getElementById('source-import')?.scrollIntoView({behavior:'smooth',block:'start'});}
 async function importNow(){setBusy('import');setError('');try{const r=await request({op:'import',rows:preview,tech,source_id:selected});setNotice(r.capture.message);setPreview([]);setResult({capture:r.capture});await refresh();}catch(e){setError(e.message);}finally{setBusy('');}}
 const queue=data.records.filter(e=>['pending','quarantine'].includes(e.review_status)),monitoring=data.monitoring;
 const sampleMonths=samples?monthsInWindow(samples.window):[],sampleSources=(samples?.sources||[]).map(s=>({...s,coverage:sampleMonths.map(month=>s.coverage.find(c=>c.month===month)||{month,status:'missing'})}));
 return <>
  <section className="card sample-sources"><h2>固定样本来源</h2>{sampleError?<p role="alert">{sampleError}</p>:!samples?<p>正在读取采集记录…</p>:<><p>尝试窗口：{samples.window.start} 至 {samples.window.end} · {sampleSources.filter(s=>s.group==='media').length} 家媒体 · {sampleSources.filter(s=>s.group==='media').reduce((n,s)=>n+s.coverage.reduce((n,c)=>n+(c.eligible||0),0),0).toLocaleString('zh-CN')} 篇去重新闻（含旧数据）</p><div className="table-scroll"><table><thead><tr><th>样本来源</th><th>去重新闻</th><th>历史覆盖</th><th>逐月覆盖</th></tr></thead><tbody>{sampleSources.map(s=><tr key={s.id}><th><a href={safeUrl(s.url)||undefined} target="_blank" rel="noreferrer">{s.name} ↗</a></th><td>{s.coverage.reduce((n,c)=>n+(c.eligible||0),0).toLocaleString('zh-CN')}</td><td>{s.coverage.every(c=>c.status==='complete')?`${s.coverage.length}个月窗口已核对`:`不完整：${s.coverage.filter(c=>c.status!=='complete').map(c=>monthLabel(c.month,samples.window)+(c.status==='stale'?'（沿用旧数据）':c.status==='missing'?'（缺口）':'')).join('、')}`}</td><td><details><summary>逐月数量与状态</summary><ul>{s.coverage.map(c=><li key={c.month}><b>{monthLabel(c.month,samples.window)} · {c.eligible??'—'} 篇 · {coverageLabel(c)}</b></li>)}</ul></details></td></tr>)}{samples.unavailable_sources?.map(s=><tr key={s.name}><th>{s.name}</th><td>未建立</td><td>未纳入分母</td><td>{s.reason}</td></tr>)}</tbody></table></div><p className="panel-note">* 非完整月 · {when(samples.collected_at)} · <a href="/sample-sources.json" download>下载采集记录</a></p></>}</section>
  <div className="source-intro"><div><strong>9 类来源 · {sourcePanel.length} 个登记入口</strong></div><span className="badge">{monitoring?.enabled?'每周更新已设置':'定时更新未开启'}</span></div>
  <section className="card source-controls"><div className="source-filters"><label>来源类别<select value={category} onChange={e=>setCategory(e.target.value)} aria-label="来源类别"><option value="all">全部九类</option>{Object.entries(CATEGORIES).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>技术主题<select value={tech} onChange={e=>changeTech(e.target.value)} aria-label="采集技术主题">{Object.entries(TECHS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="wide">栏目关键词（任一词匹配）<input aria-label="栏目关键词" value={keyword} maxLength={200} onChange={e=>setKeyword(e.target.value)}/></label></div><div className="source-actions"><button className="button primary" disabled={!!busy||!keyword.trim()||!shown.some(s=>s.mode==='public')} onClick={()=>check()}><RefreshCw size={15}/>检查本组公开来源（{shown.filter(s=>s.mode==='public').length}）</button>{busy==='check'&&<button className="button secondary" onClick={()=>{cancelled.current=true;}}>停止后续检查</button>}<span className="muted" aria-live="polite">{progress}</span></div></section>
  {error&&<p className="error" role="alert">{error}</p>}{notice&&<div className="notice" role="status"><CheckCircle2 size={17}/>{notice}</div>}
  <div className="source-layout"><section className="card source-directory" aria-label="来源目录">{shown.map(s=>{const audit=rolling.sources.find(x=>x.source_id===s.id)||remediation.sources.find(x=>x.source_id===s.id),logged=checks[s.id],c=logged&&(!audit||new Date(logged.captured_at)>=new Date(audit.checked_at))?logged:null;return <button key={s.id} aria-pressed={selected===s.id} className={'source-choice '+(selected===s.id?'chosen':'')} onClick={()=>{setSelected(s.id);setResult(null);}}><span><strong>{s.name}</strong><small>{CATEGORIES[s.category]}{audit?` · ${audit.label}`:''}</small></span><span className={'badge '+(c?.status==='discovered'?'green':'')}>{c?labels[c.status]:modeLabel[s.mode]}</span></button>;})}</section>
   <section className="card source-detail"><div className="section-heading"><div><p className="eyebrow">{CATEGORIES[source.category]}</p><h2>{source.name}</h2></div><span className="badge">{modeLabel[source.mode]}</span></div><div className="actions"><a className="button secondary" href={source.url} target="_blank" rel="noreferrer">官方入口<ArrowUpRight size={15}/></a><a className="button secondary" href={`https://www.bing.com/search?q=${encodeURIComponent(query)}`} target="_blank" rel="noreferrer">定向检索<Search size={15}/></a>{source.mode==='public'&&<button className="button primary" disabled={!!busy||!keyword.trim()} onClick={()=>check(source)}>检查此栏目</button>}</div>
    {followup&&<div className="source-check"><strong>{followup.label} · {followup.checked_at}</strong>{followup.assistance&&<><p>待协助：{followup.assistance.task}</p>{safeUrl(followup.assistance.url)&&<a className="text-button" href={safeUrl(followup.assistance.url)} target="_blank" rel="noreferrer">查询入口 ↗</a>}<button className="text-button" onClick={()=>assist(source.id)}>提交资料</button></>}</div>}
    {currentCheck&&<div className="source-check"><strong>{labels[currentCheck.status]} · {when(currentCheck.captured_at)}</strong><p>{currentCheck.message}</p><small>检查范围：{currentCheck.url}</small>{currentCheck.status==='discovered'&&<p>本页匹配 {currentCheck.candidates?.length||0} 条线索</p>}</div>}
    <div className="candidate-list">{currentCheck?.candidates?.map(c=><div className="candidate" key={c.url}><a href={c.url} target="_blank" rel="noreferrer">{c.title}<ArrowUpRight size={12}/></a><div><small>{new URL(c.url).hostname} · {c.format==='pdf'?'PDF':'网页'}</small><button className="text-button" disabled={!!busy} onClick={()=>c.collectable?collect(c.url,c.title):(setDraft({title:c.title,url:c.url,excerpt:'',published_date:''}),setPreview([]),setNotice('已将线索填入导入区，请补充正文后预览导入。'))}>{c.collectable?'采集原文':'转入导入区'}</button></div></div>)}</div>
   </section></div>
  <div className="collection-grid"><section className="card"><div className="section-heading"><div><h2>采集原文或公众号链接</h2></div></div><form className="edit-form" onSubmit={e=>{e.preventDefault();collect();}}><label>原文 HTTPS 链接<input type="url" required value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://mp.weixin.qq.com/s/…"/></label><button className="button primary" disabled={!!busy}>{busy==='collect'?'正在提取…':'提取原文'}</button></form>{result&&result.capture.kind!=='discover'&&<div className="source-check"><strong>{labels[result.capture.status]||result.capture.status}</strong><p>{result.capture.message||result.capture.title}</p>{result.capture.excerpt&&<details><summary>查看提取正文</summary><pre>{result.capture.excerpt}</pre></details>}{result.record&&<button className="text-button" onClick={()=>inspect(result.record)}>查看记录并核验<ChevronRight size={14}/></button>}</div>}</section>
   <section className="card import-card" id="source-import"><div className="section-heading"><div><h2>文件与正文导入</h2></div><Upload size={20}/></div><div className="edit-form"><label>选择 CSV / JSON / TXT / PDF<input aria-label="选择资料文件" type="file" accept=".csv,.json,.txt,.pdf" disabled={!!busy} onChange={e=>{fileChanged(e.target.files?.[0]);e.target.value='';}}/></label><a className="text-button" href="/source-import-template.csv" download>下载 CSV 模板</a><p className="muted">标题与 HTTPS 链接必填 · 每批最多 50 条。{fileLabel&&` 当前文件：${fileLabel}`}</p><label>标题<input aria-label="导入标题" maxLength={300} value={draft.title} onChange={e=>{setDraft({...draft,title:e.target.value});setPreview([]);}}/></label><label>原文 HTTPS 链接<input aria-label="导入原文链接" type="url" value={draft.url} onChange={e=>{setDraft({...draft,url:e.target.value});setPreview([]);}}/></label><label>发布日期（未知留空）<input aria-label="导入发布日期" type="date" value={draft.published_date} onChange={e=>{setDraft({...draft,published_date:e.target.value});setPreview([]);}}/></label><label>正文片段 / PDF 提取结果<textarea aria-label="导入正文" rows={5} maxLength={16000} value={draft.excerpt} onChange={e=>{setDraft({...draft,excerpt:e.target.value});setPreview([]);}}/></label><details><summary>补充项目与金额（可选）</summary><div className="form-grid">{[['event_date','事件日期','date'],['project_id','项目编号','text'],['lot','标包','text'],['customer','买方','text'],['amount_cny','金额','number']].map(([key,label,type])=><label key={key}>{label}<input aria-label={'导入'+label} type={type} min={type==='number'?'0':undefined} step={type==='number'?'any':undefined} value={draft[key]??''} onChange={e=>{setDraft({...draft,[key]:e.target.value});setPreview([]);}}/></label>)}{[['stage','项目阶段',STAGES],['source_type','来源角色',SOURCES],['amount_kind','金额类型',AMOUNTS],['amount_scope','金额范围',SCOPES],['amount_unit','金额单位',{元:'人民币元',万元:'人民币万元',亿元:'人民币亿元'}]].map(([key,label,options])=><label key={key}>{label}<select aria-label={'导入'+label} value={draft[key]||''} onChange={e=>{setDraft({...draft,[key]:e.target.value});setPreview([]);}}><option value="">{key==='amount_unit'?'人民币元（默认）':'尚未确定'}</option>{Object.entries(options).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>)}</div></details><button className="button secondary" disabled={!!busy} onClick={previewText}>预览正文导入</button></div></section></div>
  {preview.length>0&&<section className="card import-preview"><div className="section-heading"><div><h2>确认导入 · {preview.length} 条</h2><p>{TECHS[tech]} · {source.name}</p></div><button className="button primary" disabled={!!busy} onClick={importNow}>{busy==='import'?'正在导入…':'全部入库（保留待核）'}</button></div>{preview.map((r,i)=><div key={i} className="candidate"><strong>{r.title}</strong><a href={r.url} target="_blank" rel="noreferrer">{r.url}</a><small>{r.published_date||'日期待确认（暂不入月格）'} · {r.amount_cny==null?'未填写确定金额':`${r.amount_cny.toLocaleString('zh-CN')}元 · ${AMOUNTS[r.amount_kind]}`} · {r.project_id||'项目编号待补'} {r.lot||''} · 正文 {r.excerpt.length} 字</small></div>)}</section>}
  <section className="card queue"><div className="section-heading"><div><h2>核验工作队列 <span className="count">{queue.length}</span></h2></div><button className="text-button" onClick={create}>手动新增</button></div>{queue.map(e=><button key={e.id} className="queue-item" onClick={()=>inspect(e)}><div><span className={'badge '+e.review_status}>{REVIEWS[e.review_status]}</span><strong>{e.title}</strong></div><ChevronRight size={16}/></button>)}</section>
 </>;
}
