'use client';
import {useEffect,useState,useRef} from 'react';
import {Search,ArrowUpRight,Upload,RefreshCw,CheckCircle2,ChevronRight} from 'lucide-react';
import {TECHS,STAGES,SOURCES,SCOPES,REVIEWS,safeUrl,monthsInWindow} from '@/lib/model';
import {AMOUNTS} from '@/lib/monthly';
import {sourcePanel,CATEGORIES} from '@/data/sources';
import {parseImport} from '@/lib/imports';
import TaxonomyGuide from './taxonomy-guide';
import taxonomy from '@/data/taxonomy.json';
import remediation from '@/data/source-remediation.json';
import rolling from '@/data/rolling-update.json';
import {CHILDREN} from '@/lib/hierarchy';

async function request(body){const r=await fetch('/api/radar',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error||'操作暂未完成');return d;}
const labels={fetched:'已提取 · 待核验',discovered:'栏目已读取',failed:'需手动处理',pdf:'PDF 待导入',imported:'已导入 · 待核验',reading:'读取中'};
const modeLabel={public:'按需读取',manual:'官方查询 / 导入',license:'文件导入 · API 未授权'};
const when=value=>value?new Date(value).toLocaleString('zh-CN'):'';
export default function SourceCenter({data,refresh,inspect,create}){
 const [samples,setSamples]=useState(null),[sampleError,setSampleError]=useState('');
 useEffect(()=>{let active=true;fetch('/sample-sources.json').then(r=>{if(!r.ok)throw Error('固定样本采集记录暂时无法读取');return r.json();}).then(d=>{if(active)setSamples(d);}).catch(e=>{if(active)setSampleError(e.message);});return()=>{active=false;};},[]);
 const [category,setCategory]=useState('all'),[selected,setSelected]=useState('h3c'),[tech,setTech]=useState('liquid_cooling'),[keyword,setKeyword]=useState('液冷 冷板 浸没式 CDU 服务器 智算'),[url,setUrl]=useState(''),[busy,setBusy]=useState(''),[notice,setNotice]=useState(''),[error,setError]=useState(''),[result,setResult]=useState(null),[progress,setProgress]=useState('');
 const [draft,setDraft]=useState({title:'',url:'',excerpt:'',published_date:''}),[preview,setPreview]=useState([]),[fileLabel,setFileLabel]=useState('');
 const cancelled=useRef(false),source=sourcePanel.find(s=>s.id===selected),shown=sourcePanel.filter(s=>category==='all'||s.category===category),checks=data.sourceChecks||{};
 const currentCheck=result?.capture?.kind==='discover'&&result.capture.source_id===selected?result.capture:checks[selected];
 const terms=taxonomy.technologies.find(t=>t.id===tech)?.include||[];
 const followup=rolling.sources.find(s=>s.source_id===selected)||remediation.sources.find(s=>s.source_id===selected);
 const query=`site:${source.hosts[0]} (${terms.map(t=>'"'+t+'"').join(' OR ')}) (采购 OR 中标 OR 验收 OR 上线 OR 扩容 OR 取消 OR 发布)`;
 function changeTech(value){setTech(value);setKeyword([...(taxonomy.technologies.find(t=>t.id===value)?.include||[]),'服务器','智算'].join(' '));}
 async function discover(s){return request({op:'discover',source_id:s.id,keyword,tech});}
 async function check(one){
  setBusy('check');setError('');setNotice('');cancelled.current=false;
  const list=one?[one]:shown.filter(s=>s.mode==='public');let done=0,ok=0;
  try{for(let i=0;i<list.length;i+=2){if(cancelled.current)break;const batch=await Promise.allSettled(list.slice(i,i+2).map(discover));for(const r of batch){done++;if(r.status==='fulfilled'){if(r.value.capture.status==='discovered')ok++;if(one)setResult(r.value);}else setError(r.reason.message);}setProgress(`已检查 ${done}/${list.length} 个来源，${ok} 个栏目可读`);await refresh();}
   setNotice(`${cancelled.current?'已停止，':''}完成 ${done} 个来源检查，${ok} 个栏目可读。结果已保存；未读取或无命中不能视为无需求。`);
  }catch(e){setError(e.message);}finally{setBusy('');setProgress('');}
 }
 async function collect(target=url,title=''){
  setBusy('collect');setError('');setNotice('');setResult(null);
  try{const r=await request({op:'collect',url:target,tech});setResult(r);
   if(r.capture.status==='pdf'){const {pdfText}=await import('@/lib/pdf-text');const bytes=Uint8Array.from(atob(r.capture.pdf_base64),c=>c.charCodeAt(0));const text=await pdfText(bytes);setDraft({title:title||'请填写 PDF 公告标题',url:r.capture.url,excerpt:text.excerpt,published_date:''});setPreview([]);setNotice('PDF 正文已放入下方导入区，请确认标题、原文链接，再预览导入。');setResult({capture:{...r.capture,pdf_base64:undefined}});}
   await refresh();
  }catch(e){setError(e.message);}finally{setBusy('');}
 }
 async function fileChanged(file){
  if(!file)return;setBusy('file');setError('');setNotice('');setPreview([]);setFileLabel(file.name);
  try{
   if(/\.pdf$/i.test(file.name)){if(file.size>5000000)throw Error('PDF 最多5 MB。');const {pdfText}=await import('@/lib/pdf-text');const r=await pdfText(new Uint8Array(await file.arrayBuffer()));setDraft({title:file.name.replace(/\.pdf$/i,''),url:'',published_date:'',excerpt:r.excerpt});setNotice('PDF 已在浏览器提取文本。补充原文链接后预览导入；不保存 PDF 原件。');}
   else{if(file.size>800000)throw Error('文件最多800 KB。');const text=await file.text();if(/\.(csv|json)$/i.test(file.name)){setPreview(parseImport(text,file.name));setNotice('已解析文件，请核对下方预览后导入。');}else if(/\.txt$/i.test(file.name)){if(text.length>16000)throw Error('TXT 正文最多16,000字，请截取相关部分。');setDraft({title:file.name.replace(/\.txt$/i,''),url:'',published_date:'',excerpt:text});setNotice('请补充标题与原文链接，再预览导入。');}else throw Error('支持 CSV、JSON、TXT 和 PDF。');}
  }catch(e){setError(e.message);}finally{setBusy('');}
 }
 function previewText(){try{setPreview(parseImport(JSON.stringify([draft]),'manual.json'));setError('');}catch(e){setError(e.message);}}
 function assist(id){setSelected(id);setCategory('all');setResult(null);document.getElementById('source-import')?.scrollIntoView({behavior:'smooth',block:'start'});}
 async function importNow(){setBusy('import');setError('');try{const r=await request({op:'import',rows:preview,tech,source_id:selected});setNotice(r.capture.message);setPreview([]);setResult({capture:r.capture});await refresh();}catch(e){setError(e.message);}finally{setBusy('');}}
 const queue=data.records.filter(e=>['pending','quarantine'].includes(e.review_status)),expansion=data.research?.expansion,monitoring=data.monitoring,months=monthsInWindow(data.research);
 return <>
  <TaxonomyGuide/>
  <section className="card" id="rolling-update"><h2>本轮滚动更新 · {rolling.checked_at.slice(0,10)}</h2><p>{rolling.summary}</p><p>已检查全部{rolling.sources.length}个登记来源（本轮新增熠知电子、云豹智能）：{rolling.source_summary.readable}个公开入口可读、{rolling.source_summary.partial}个替代入口部分可读、{rolling.source_summary.restricted}个访问受限、{rolling.source_summary.manual}个动态查询或需手动/授权。入口检查完成不等于数据全量接通。</p><p><a href="/rolling-update.json" download>下载本轮结果与逐源状态</a> · <a href="/rolling-preview-news.json" download>下载窗口外新闻预览</a></p><details><summary>本批补采原文来源 · {rolling.backfill_sources.length}个站点</summary>{rolling.backfill_sources.map(s=><p key={s.host}><a href={safeUrl(s.url)||undefined} target="_blank" rel="noreferrer">{s.publisher} ↗</a> · {s.host} · 补录{s.records}条</p>)}</details><details><summary>9月21—23日新发现 · 下轮统计预览（{rolling.preview.length}条重点线索）</summary><p>这些线索尚未进入截至{rolling.cutoff}的完整周图表；原文可读不等于实际采购。全部媒体预览{rolling.preview_news_rows}条，其中C114的9月23日归档日期检查未通过，已标记待复核。</p>{rolling.preview.map((r,i)=><p key={i}><time>{r.published_date||r.date}</time> · <a href={safeUrl(r.url)||undefined} target="_blank" rel="noreferrer">{r.title} ↗</a></p>)}</details><p className="footnote">补采增加历史收录量，不能解释为本周市场增长。四媒体完成9月7—20日回查；商业API与公众号后台授权状态保留。</p></section>
  <section className="card sample-sources" id="source-followup"><h2>前次补采归档与待协助</h2><p>{remediation.checked_at}核查 {remediation.sources.length} 个来源 · 本批新增 {data.records.filter(e=>remediation.record_ids.includes(e.id)).length} 条已同步到统一台账。补查窗口 {remediation.window.start} 至 {remediation.window.end}，包括待核线索；定向补查不代表完整覆盖。</p><p>优先协助清单已列在各来源下方。新资料可点“提交资料”导入；已收录的项目请点下方记录补证，避免重复入库。<a href="/source-remediation.json" download>下载本批采集与协助清单</a></p><details><summary>查看各来源进展与具体操作</summary>{remediation.sources.map(s=><details className="research-record" key={s.source_id}><summary><span><b>{sourcePanel.find(x=>x.id===s.source_id)?.name||s.source_id}</b><small>{s.label} · 新增 {data.records.filter(e=>s.record_ids.includes(e.id)).length} 条</small></span><span>{s.assistance?.priority==='P1'?'优先协助':s.assistance?'可补资料':'已检查'} ▾</span></summary><div className="record-body"><p><b>本次结果：</b>{s.result}</p><p><b>覆盖与缺口：</b>{s.coverage}（{s.checked_at}）</p><p>{s.public_urls?.map((u,i)=><a key={u} href={safeUrl(u)||undefined} target="_blank" rel="noreferrer">公开来源 {i+1} ↗　</a>)}</p>{s.assistance?<><p><b>{s.assistance.priority==='optional'?'可选资料':'需要协助'}：</b>{s.assistance.task}</p>{s.assistance.query&&<p>检索：{s.assistance.query}</p>}<p><a href={safeUrl(s.assistance.url)||undefined} target="_blank" rel="noreferrer">打开查询入口 ↗</a></p><button className="button secondary" onClick={()=>assist(s.source_id)}>提交{sourcePanel.find(x=>x.id===s.source_id)?.name||s.source_id}资料</button></>:<p>本轮已有公开获取路径；后续继续补采。</p>}{data.records.filter(e=>s.record_ids.includes(e.id)).map(e=><p key={e.id}><button className="text-button" onClick={()=>inspect(e)}>查看 / 补证：{e.title}</button></p>)}</div></details>)}</details>{remediation.references?.length>0&&<details><summary>行业参考资料 · 不计入项目图表</summary>{remediation.references.map(e=><p key={e.id}><a href={safeUrl(e.url)||undefined} target="_blank" rel="noreferrer">{e.title} ↗</a> · {e.published_date}；未证明符合目标项目定义。</p>)}</details>}<p className="footnote">“已补采”不代表全量接通；商业 API 未开通。已导入记录保留核验状态，日期落在研究窗口内即进入月度信息量；金额明确后进入合并金额图。市场风向仍使用固定媒体全新闻分母。</p></section>
  {monitoring&&<section className="card"><h2>每周更新与异动提示</h2><p><strong>{monitoring.schedule_label}</strong> · {monitoring.enabled?'定时任务已设置':'尚未启用'} · 覆盖5个父类、14个观察子项，重点海光与鲲鹏。</p><p>{monitoring.latest_status}。{monitoring.last_completed_cutoff?`最近按周规范更新的数据截止：${monitoring.last_completed_cutoff}`:`首次计划：${when(monitoring.first_run)}；当前数据基线：${monitoring.baseline_as_of}`}</p><details><summary>查看更新范围与提醒规则</summary><p>每周增量采集、回查前14天；同步市场风向、月度研究、金额与来源清单。完整周与前4周比较，固定媒体仍以全部新闻为分母。</p><p>{monitoring.rule_summary}</p><p>提示包含原文、证据状态及业务判断；来源缺失和采集异常单独提示，不作需求下降解释。没有重要异动时照常更新并保持安静。本地监测输出见 weekly-runs；如需通知，应另行配置自己的调度和通知渠道。</p><p className="muted">{monitoring.execution}</p></details><p>本轮比较：{rolling.monitoring.window.start}—{rolling.monitoring.window.end}，对照前4周 {rolling.monitoring.window.baseline_start}—{rolling.monitoring.window.baseline_end}。</p>{monitoring.latest_alerts?.map(a=><article className="capture-row" key={a.id}><div><strong>{a.title}</strong><p>{a.detail}</p>{safeUrl(a.url)&&<a href={safeUrl(a.url)} target="_blank" rel="noreferrer">查看原文 ↗</a>}</div></article>)}</section>}
  <section className="card sample-sources"><h2>市场风向 · 固定样本采集记录</h2>{sampleError?<p role="alert">{sampleError}</p>:!samples?<p>正在读取采集记录…</p>:<><p>{samples.window.start} 至 {samples.window.end} · {samples.sources.filter(s=>s.group==='media').length} 家媒体 · {samples.sources.filter(s=>s.group==='media').reduce((n,s)=>n+s.coverage.reduce((n,c)=>n+(c.eligible||0),0),0).toLocaleString('zh-CN')} 篇去重新闻。与市场风向同步更新；官网单列，不计入媒体合计。</p><div className="table-scroll"><table><thead><tr><th>样本来源</th><th>去重新闻</th><th>历史覆盖</th><th>采集范围与方法</th></tr></thead><tbody>{samples.sources.map(s=><tr key={s.id}><th><a href={safeUrl(s.url)||undefined} target="_blank" rel="noreferrer">{s.name} ↗</a></th><td>{s.coverage.reduce((n,c)=>n+(c.eligible||0),0).toLocaleString('zh-CN')}</td><td>{s.coverage.every(c=>c.status==='complete')?`${s.coverage.length}个月窗口已核对`:`不完整：${s.coverage.filter(c=>c.status!=='complete').map(c=>Number(c.month.slice(5))+'月').join('、')}`}</td><td><details><summary>查看方法与逐月数量</summary><p>{s.method}</p><p>{s.coverage.map(c=>`${Number(c.month.slice(5))}月 ${c.eligible??'缺失'}${c.status==='complete'?'':'（覆盖不完整）'}`).join('；')}</p><p>{s.limitation}</p></details></td></tr>)}{samples.unavailable_sources?.map(s=><tr key={s.name}><th>{s.name}</th><td>未建立</td><td>未纳入分母</td><td>{s.reason}</td></tr>)}</tbody></table></div><p className="panel-note">数据截至{samples.window.end}，非完整月不作完整月比较。批次记录时间：{when(samples.collected_at)}。下方“检查栏目”只检查当前页，不会重算历史样本分母。<a href="/sample-sources.json" download>下载采集记录</a></p></>}</section>
  {expansion&&<section className="card"><h2>月度研究 · 本轮扩样来源</h2><p>{expansion.summary}</p><details className="research-record"><summary>查看本轮 {expansion.sources.length} 个来源站点及月份覆盖</summary><div className="table-scroll"><table><thead><tr><th>来源站点</th><th>新增记录</th><th>有收录的月份</th><th>获取方法</th></tr></thead><tbody>{expansion.sources.map(s=><tr key={s.host}><th><a href={safeUrl(s.url)||undefined} target="_blank" rel="noreferrer">{s.name} ↗</a><small>{s.host}</small></th><td>{s.records}</td><td>{s.months.map(m=>Number(m.slice(5))+'月').join('、')}</td><td>{s.method}</td></tr>)}</tbody></table></div></details><p className="footnote">以上为{expansion.retrieved_on}扩样批次的来源归档，月份表示有收录，不表示全量覆盖。官网历史目录、公开月报与采购原文补充到事件台账；不改变市场风向的全新闻分母。转载归并，未取得原始披露的保留待核，未接入付费数据库或公众号后台。</p></section>}
  <div className="source-intro"><div><strong>9 类来源 · {sourcePanel.length} 个登记入口</strong><p>按需检查公开栏目，采集原文或导入资料，即可纳入统一数据库，保留待核状态。</p></div><span className="badge">{monitoring?.enabled?'每周更新已设置':'定时更新未开启'}</span></div>
  <section className="card source-controls"><div className="source-filters"><label>来源类别<select value={category} onChange={e=>setCategory(e.target.value)} aria-label="来源类别"><option value="all">全部九类</option>{Object.entries(CATEGORIES).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>技术主题<select value={tech} onChange={e=>changeTech(e.target.value)} aria-label="采集技术主题">{Object.entries(TECHS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="wide">栏目关键词（任一词匹配）<input aria-label="栏目关键词" value={keyword} maxLength={200} onChange={e=>setKeyword(e.target.value)}/></label></div><div className="source-actions"><button className="button primary" disabled={!!busy||!keyword.trim()||!shown.some(s=>s.mode==='public')} onClick={()=>check()}><RefreshCw size={15}/>检查本组公开来源（{shown.filter(s=>s.mode==='public').length}）</button>{busy==='check'&&<button className="button secondary" onClick={()=>{cancelled.current=true;}}>停止后续检查</button>}<span className="muted" aria-live="polite">{progress||'仅检查当前栏目页，不遍历全部历史；本次结果会保存。'}</span></div></section>
  {error&&<p className="error" role="alert">{error}</p>}{notice&&<div className="notice" role="status"><CheckCircle2 size={17}/>{notice}</div>}
  <div className="source-layout"><section className="card source-directory" aria-label="来源目录">{shown.map(s=>{const audit=rolling.sources.find(x=>x.source_id===s.id)||remediation.sources.find(x=>x.source_id===s.id),logged=checks[s.id],c=logged&&(!audit||new Date(logged.captured_at)>=new Date(audit.checked_at))?logged:null;return <button key={s.id} aria-pressed={selected===s.id} className={'source-choice '+(selected===s.id?'chosen':'')} onClick={()=>{setSelected(s.id);setResult(null);}}><span><strong>{s.name}</strong><small>{CATEGORIES[s.category]}{audit?` · ${audit.label}`:''}</small></span><span className={'badge '+(c?.status==='discovered'?'green':'')}>{c?labels[c.status]:modeLabel[s.mode]}</span></button>;})}<p className="footnote">此目录是首批固定观察入口。地方平台、银行、医院、云厂商及新增公众号可经原文或文件导入；未登记为全量覆盖。</p></section>
   <section className="card source-detail"><div className="section-heading"><div><p className="eyebrow">{CATEGORIES[source.category]}</p><h2>{source.name}</h2></div><span className="badge">{modeLabel[source.mode]}</span></div><p className="muted">{source.note}</p><div className="actions"><a className="button secondary" href={source.url} target="_blank" rel="noreferrer">官方入口<ArrowUpRight size={15}/></a><a className="button secondary" href={`https://www.bing.com/search?q=${encodeURIComponent(query)}`} target="_blank" rel="noreferrer">定向检索<Search size={15}/></a>{source.mode==='public'&&<button className="button primary" disabled={!!busy||!keyword.trim()} onClick={()=>check(source)}>检查此栏目</button>}</div><p className="query-preview">{query}</p>
    {source.mode==='license'&&<p className="soft-note">商业 API 尚未开通；本轮已检查公开线索与官方替代入口。可导入已有资料，无需为本次补采购买服务。</p>}
    {followup&&<div className="source-check"><strong>本轮补采：{followup.label} · {followup.checked_at}</strong><p>{followup.result}</p><p>{followup.coverage}</p>{followup.assistance&&<p>待协助：{followup.assistance.task}</p>}</div>}
    {currentCheck&&<div className="source-check"><strong>站内读取日志：{labels[currentCheck.status]} · {when(currentCheck.captured_at)}</strong><p>{currentCheck.message}</p><small>检查范围：{currentCheck.url}</small>{currentCheck.status==='discovered'&&<p>本页匹配 {currentCheck.candidates?.length||0} 条线索。标题匹配不代表满足技术定义。</p>}</div>}
    <div className="candidate-list">{currentCheck?.candidates?.map(c=><div className="candidate" key={c.url}><a href={c.url} target="_blank" rel="noreferrer">{c.title}<ArrowUpRight size={12}/></a><div><small>{new URL(c.url).hostname} · {c.format==='pdf'?'PDF':'网页'}</small><button className="text-button" disabled={!!busy} onClick={()=>c.collectable?collect(c.url,c.title):(setDraft({title:c.title,url:c.url,excerpt:'',published_date:''}),setPreview([]),setNotice('已将线索填入导入区，请补充正文后预览导入。'))}>{c.collectable?'采集原文':'转入导入区'}</button></div></div>)}</div>
   </section></div>
  <div className="collection-grid"><section className="card"><div className="section-heading"><div><h2>采集原文或公众号链接</h2><p>登记站点的公开 HTML / PDF · 新记录全部待核验。</p></div></div><form className="edit-form" onSubmit={e=>{e.preventDefault();collect();}}><label>原文 HTTPS 链接<input type="url" required value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://mp.weixin.qq.com/s/…"/></label><button className="button primary" disabled={!!busy}>{busy==='collect'?'正在提取…':'提取原文'}</button></form><p className="soft-note">公众号只尝试读取已知文章链接，不自动遍历账号历史或抓取阅读量。验证码、登录、动态内容、抓取规则限制会保留为未提取；可在右侧导入正文。</p>{result&&result.capture.kind!=='discover'&&<div className="source-check"><strong>{labels[result.capture.status]||result.capture.status}</strong><p>{result.capture.message||result.capture.title}</p>{result.capture.excerpt&&<pre>{result.capture.excerpt}</pre>}{result.record&&<button className="text-button" onClick={()=>inspect(result.record)}>查看记录并核验<ChevronRight size={14}/></button>}</div>}</section>
   <section className="card import-card" id="source-import"><div className="section-heading"><div><h2>文件与正文导入</h2><p>适用于地方采购、公众号、商业导出及 PDF 公告。</p></div><Upload size={20}/></div><div className="edit-form"><label>选择 CSV / JSON / TXT / PDF<input aria-label="选择资料文件" type="file" accept=".csv,.json,.txt,.pdf" disabled={!!busy} onChange={e=>{fileChanged(e.target.files?.[0]);e.target.value='';}}/></label><a className="text-button" href="/source-import-template.csv" download>下载 CSV 模板</a><p className="muted">支持中文模板，标题与HTTPS链接必填；日期、项目编号、标包、阶段、技术分类、芯片、金额与类型可一起导入。金额单位支持元／万元／亿元，每批最多50条；纯CPU资料可填写“常规芯片采购补充”和对应芯片路线。{fileLabel&&` 当前文件：${fileLabel}`}</p><label>标题<input aria-label="导入标题" maxLength={300} value={draft.title} onChange={e=>{setDraft({...draft,title:e.target.value});setPreview([]);}}/></label><label>原文 HTTPS 链接<input aria-label="导入原文链接" type="url" value={draft.url} onChange={e=>{setDraft({...draft,url:e.target.value});setPreview([]);}}/></label><label>发布日期（未知留空）<input aria-label="导入发布日期" type="date" value={draft.published_date} onChange={e=>{setDraft({...draft,published_date:e.target.value});setPreview([]);}}/></label><label>正文片段 / PDF 提取结果<textarea aria-label="导入正文" rows={5} maxLength={16000} value={draft.excerpt} onChange={e=>{setDraft({...draft,excerpt:e.target.value});setPreview([]);}}/></label><details><summary>补充项目与金额（可选）</summary><div className="form-grid">{[['event_date','事件日期','date'],['project_id','项目编号','text'],['lot','标包','text'],['customer','买方','text'],['amount_cny','金额','number']].map(([key,label,type])=><label key={key}>{label}<input aria-label={'导入'+label} type={type} min={type==='number'?'0':undefined} step={type==='number'?'any':undefined} value={draft[key]??''} onChange={e=>{setDraft({...draft,[key]:e.target.value});setPreview([]);}}/></label>)}{[['stage','项目阶段',STAGES],['source_type','来源角色',SOURCES],['amount_kind','金额类型',AMOUNTS],['amount_scope','金额范围',SCOPES],['amount_unit','金额单位',{元:'人民币元',万元:'人民币万元',亿元:'人民币亿元'}]].map(([key,label,options])=><label key={key}>{label}<select aria-label={'导入'+label} value={draft[key]||''} onChange={e=>{setDraft({...draft,[key]:e.target.value});setPreview([]);}}><option value="">{key==='amount_unit'?'人民币元（默认）':'尚未确定'}</option>{Object.entries(options).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>)}</div><p className="muted">金额须同时选择类型；不同标包分行。预计区间可通过JSON的amount_range_cny导入，上下限单位为人民币元。新导入一律保留待核。</p></details><button className="button secondary" disabled={!!busy} onClick={previewText}>预览正文导入</button></div></section></div>
  {preview.length>0&&<section className="card import-preview"><div className="section-heading"><div><h2>确认导入 · {preview.length} 条</h2><p>技术：{TECHS[tech]} · 来源入口：{source.name}。同一原文、明确项目编号和标包跳过，不覆盖已有笔记；不同项目或标包分别保留，编号歧义时提示补齐。</p></div><button className="button primary" disabled={!!busy} onClick={importNow}>{busy==='import'?'正在导入…':'全部入库（保留待核）'}</button></div>{preview.map((r,i)=><div key={i} className="candidate"><strong>{r.title}</strong><a href={r.url} target="_blank" rel="noreferrer">{r.url}</a><small>{r.published_date||'日期待确认（暂不入月格）'} · {r.amount_cny==null?'未填写确定金额':`${r.amount_cny.toLocaleString('zh-CN')}元 · ${AMOUNTS[r.amount_kind]}`} · {r.project_id||'项目编号待补'} {r.lot||''} · 正文 {r.excerpt.length} 字</small></div>)}</section>}
  <section className="card queue"><div className="section-heading"><div><h2>核验工作队列 <span className="count">{queue.length}</span></h2><p>以下记录均已入库并纳入默认信息量统计；继续核对正文、主体和阶段，提升证据可信度。</p></div><button className="text-button" onClick={create}>手动新增</button></div>{queue.map(e=><button key={e.id} className="queue-item" onClick={()=>inspect(e)}><div><span className={'badge '+e.review_status}>{REVIEWS[e.review_status]}</span><strong>{e.title}</strong><p>{e.limitations}</p></div><ChevronRight size={16}/></button>)}</section>
  <section className="card"><h2>月度研究检索归档</h2><p>{data.research.queries.length} 条检索日志 · {new Set(data.research.queries.filter(q=>CHILDREN[q.category]&&months.includes(q.month)).map(q=>q.category+'|'+q.month)).size} / {Object.keys(CHILDREN).length*months.length} 个分类月份格。研究截止 {data.as_of}，与下方站内实际读取记录分别保留。</p><details><summary>查看月度检索记录</summary>{data.research.queries.map((q,i)=><div className="capture-row" key={i}><span>{q.month}</span><div><strong>{CHILDREN[q.category]||q.category} · {q.query}</strong><small>{q.result_summary||q.note||'详见完整研究包'}</small></div></div>)}</details><p className="muted">检索记录随页面顶部“备份数据”导出；执行过检索不代表全网覆盖。</p></section>
  <section className="card capture-log"><h2>最近读取与导入记录</h2>{data.captures.map(c=><div className="capture-row" key={c.id}><span className={'badge '+(['fetched','discovered','imported'].includes(c.status)?'green':'pending')}>{labels[c.status]||c.status}</span><div><a href={safeUrl(c.url)||undefined} target="_blank" rel="noreferrer">{c.title||c.url}</a><small>{c.message||c.url}</small></div><time>{when(c.captured_at)}</time></div>)}</section>
 </>;
}
