'use client';
import {useState,useEffect,useRef} from 'react';
import {LayoutDashboard,Files,Search,BookOpen,Plus,ArrowUpRight,Download,ShieldCheck,ChevronRight,X,RefreshCw,CheckCircle2} from 'lucide-react';
import {TECHS,STAGES,SOURCES,REVIEWS,SCOPES,safeUrl} from '@/lib/model';
import TaxonomyGuide from './taxonomy-guide';
import taxonomy from '@/data/taxonomy.json';
import SourceCenter from './source-center';
import MonthlyResearch from './monthly-research';
import MarketPanel from './market-panel';
import ResearchLog from './research-log';
import initialResearch from '@/data/research-2026.json';
import initialMonitoring from '@/data/weekly-monitor.json';
import ResearchEditor from './research-editor';
import {AMOUNTS} from '@/lib/monthly';
const NAV=[['panel','市场风向',LayoutDashboard],['monthly','月度事件',Files],['collect','来源与采集',Search],['log','日志',BookOpen]];
const money=e=>e.amount_range_cny?`¥${e.amount_range_cny.min.toLocaleString('zh-CN')}—${e.amount_range_cny.max.toLocaleString('zh-CN')}（预计）`:e.value_cny==null?'金额未披露':`¥${Number(e.value_cny).toLocaleString('zh-CN')}`;
async function api(body){const r=await fetch('/api/radar',body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||'暂时无法连接，请稍后再试');return d;}
function download(name,content,type){const u=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function Badge({kind,children}){return <span className={`badge ${kind||''}`}>{children}</span>;}
export default function Workspace(){
 const [data,setData]=useState(null),[loadError,setLoadError]=useState(''),[view,setView]=useState('monthly'),[toast,setToast]=useState(''),[modal,setModal]=useState(null);
 async function refresh(){try{const d=await api();setData(d);setLoadError('');return d;}catch(e){setLoadError(e.message);throw e;}}
 useEffect(()=>{refresh().catch(()=>{});},[]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(t);}},[toast]);
 const research=data?.research||initialResearch,monitoring=data?.monitoring||initialMonitoring;
 function create(){const id=crypto.randomUUID();editResearch('leads',id,{id,title:'',url:'',publisher:'',customer:'',project_id:id,event_key:id,published_date:'',event_date:null,stage:'research',source_type:'unknown',categories:[],tags:[],amount_cny:null,amount_kind:'none',amount_scope:'unknown',amount_text:'',fact_summary:'',limitations:'',verified_fulltext:false,amount_eligible:false,evidence_status:'lead',_revision:0});}
 function editResearch(section,key,record){setModal({mode:'research',section,key,record});}
 function editRecord(record){editResearch(record._ref?.section||'events',record.id,record);}
 async function saveResearch(payload){await api({...payload,op:modal.record._ref?.source==='workspace'?'save_workspace_research':'save_research'});await refresh();setModal(null);setToast('已保存');}
 return <div className="shell"><aside className="sidebar"><div className="brand"><img className="brand-symbol" src="/isg-radar-mark.png" width="52" height="52" alt=""/><div><strong>ISG</strong><span>技术情报台</span></div></div><p className="nav-caption">中国服务器市场</p><nav aria-label="主导航">{NAV.map(([id,label,Icon])=><button key={id} className={view===id?'active':''} onClick={()=>setView(id)} aria-current={view===id?'page':undefined}><Icon size={19}/>{label}<ChevronRight size={15}/></button>)}</nav><div className="sidebar-bottom"><ShieldCheck size={17}/><div>固定样本 · 可追溯<span>关注、需求与落地分开观察</span></div></div></aside><main><header className="topbar"><span>市场战略 <span className="slash">/</span> 竞争跟踪</span></header><div className="content"><div className="page-heading"><div><h1>{NAV.find(n=>n[0]===view)?.[1]}</h1></div>{view!=='panel'&&<div className="actions"><button className="button secondary" disabled={!data} onClick={()=>download('ISG研究台账备份.json',JSON.stringify({exported_at:new Date().toISOString(),...data},null,2),'application/json')}><Download size={16}/>备份数据</button><button className="button secondary" onClick={()=>refresh().catch(()=>{})}><RefreshCw size={15}/>刷新台账</button>{view!=='log'&&<button className="button primary" disabled={!data} onClick={create}><Plus size={16}/>新增线索</button>}</div>}</div>
 {loadError&&view!=='panel'&&<div className="notice error" role="alert">{loadError}<button className="text-button" onClick={()=>refresh().catch(()=>{})}>重新加载</button></div>}
 {view==='panel'&&<MarketPanel/>}
 {view==='monthly'&&<MonthlyResearch research={research} onEdit={data?editResearch:null}/>}
 {view==='collect'&&(data?<><SourceCenter data={data} refresh={refresh} inspect={record=>setModal({mode:'detail',record:data.records.find(e=>e.id===record.id)||record})} create={create}/></>:<p>正在读取来源台账…</p>)}
 {view==='log'&&<ResearchLog data={data} research={research} monitoring={monitoring} onEdit={data?editResearch:null} method={<Method/>}/>}
 <footer>研究窗口：{research.period_start} 至 {research.period_end}<span>媒体更新截至：{monitoring.last_completed_cutoff||'尚未完成'}{monitoring.latest_requested_cutoff&&` · 最近尝试至 ${monitoring.latest_requested_cutoff}${monitoring.latest_update_status==='partial'?'（部分更新）':''}`}</span></footer></div></main>{toast&&<div className="toast" role="status"><CheckCircle2 size={18}/>{toast}</div>}
 {modal?.mode==='research'&&<Dialog title="编辑项目与研究笔记" close={()=>setModal(null)}><ResearchEditor section={modal.section} itemKey={modal.key} record={modal.record} save={saveResearch}/></Dialog>}
 {modal?.mode==='detail'&&<Dialog title="证据详情" close={()=>setModal(null)}><Detail record={modal.record} edit={()=>editRecord(modal.record)}/></Dialog>}
 </div>;
}
function Dialog({title,close,children}){const ref=useRef(null);useEffect(()=>{ref.current?.showModal();},[]);return <dialog ref={ref} onCancel={e=>{e.preventDefault();close();}} className="drawer" aria-label={title}><div className="drawer-top"><strong>{title}</strong><button className="icon-button" aria-label="关闭详情" onClick={close}><X size={20}/></button></div><div className="drawer-body">{children}</div></dialog>;}
function Detail({record:e,edit}){const [history,setHistory]=useState(null),[error,setError]=useState('');useEffect(()=>{let active=true;fetch(`/api/radar?history=${encodeURIComponent(e.id)}`,{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);if(active)setHistory(d.history);}).catch(x=>{if(active)setError(x.message);});return()=>{active=false;};},[e.id,e.revision]);return <><div className="detail-tags"><Badge kind={e.review_status}>{REVIEWS[e.review_status]}</Badge><Badge>{STAGES[e.stage]}</Badge>{e.techs.map(t=><Badge key={t}>{TECHS[t]}</Badge>)}</div><h2 className="detail-title">{e.title}</h2><p className="muted">{e.publisher} · 披露于 {e.published_date||'待确认'}</p><div className="actions detail-actions"><a className="button secondary" href={safeUrl(e.url)||undefined} target="_blank" rel="noreferrer"><ArrowUpRight size={16}/>阅读原文</a><button className="button primary" onClick={edit}>编辑与核验</button></div><dl className="detail-grid"><div><dt>买方主体</dt><dd>{e.customer||'未披露 / 不适用'}</dd></div><div><dt>来源角色</dt><dd>{SOURCES[e.source_type]}</dd></div><div><dt>事件日期</dt><dd>{e.event_date||'未明确，按披露日观察'}</dd></div><div><dt>披露金额</dt><dd>{money(e)}<small>{AMOUNTS[e.amount_kind]||'口径待核'} · {SCOPES[e.amount_scope]}</small></dd></div></dl>{[['原文摘录',e.source_excerpt||e.evidence_excerpt],['分类口径',e.classification_note],['事实摘要',e.fact_summary],['金额原文',e.amount_text],['战略判断 · 推断',e.implication],['证据局限 / 待确认',e.limitations],['共享研究笔记',e.note]].filter(([label,text])=>!['分类口径','原文摘录','金额原文'].includes(label)||text).map(([label,text])=><section className="detail-section" key={label}><h3>{label}</h3><p>{text||'尚未填写'}</p></section>)}{!!e.competitors?.length&&<section className="detail-section"><h3>相关厂商与角色</h3>{e.competitors.map((c,i)=><p key={i}>{c.name} · {c.role}</p>)}</section>}<div className="soft-note">项目编号：{e.project_id}<br/>事件编号：{e.event_key}<br/>下一次核查：{e.followup_on||'未设置'}（日期标记，不自动提醒）</div><details className="history"><summary>修改记录 · 当前版本 {e.revision}</summary>{error?<p className="error">{error}</p>:history===null?<p>正在加载…</p>:history.length?history.map(h=><p key={`${h.source}-${h.data.id}-${h.data.revision}`}>{h.source} · 版本 {h.data.revision} · {new Date(h.at).toLocaleString('zh-CN')} · {REVIEWS[h.data.review_status]||h.data.value?.evidence_status}</p>):<p>初始导入，暂无后续修改。</p>}</details></>;}
function Method(){return <div className="panel-method"><TaxonomyGuide/><section className="card"><h2>固定样本中的占比与变化</h2><p>市场风向收集四家固定媒体的全部去重新闻作为分母，包括未命中观察主题及非基础设施新闻。项目台账用于解释具体变化，不再作为市场趋势的分母。</p><dl><dt>采购需求占比</dt><dd>明确要求某技术的采购标包 ÷ 同来源、同月适用的全部采购标包。按项目及标包归并，变更与终止保留状态。分母范围随技术不同，不能直接跨技术排名。</dd><dt>标题中的采购与部署表述占比</dt><dd>标题同时提及技术和试用、采购、部署或扩容的新闻 ÷ 固定来源同期全部去重新闻。观察报道内容结构，不等同于客户实际采用率。</dd><dt>标题提及份额</dt><dd>标题提及某技术的新闻 ÷ 固定来源同期全部去重新闻。多标签可以重叠，各技术份额不相加。</dd></dl></section><section className="card"><h2>可比性规则</h2><ol><li>同一条趋势使用同一个固定来源，来源之间分别查看。新增来源先回补历史，不能直接拼进旧趋势。</li><li>正文未取得、页码缺失、栏目历史不完整时标记缺口；分母为零显示不适用，已完整观察但未提及才显示0‰。</li><li>每个读数同时展示分子、分母。小样本只提供描述，按季度合并时先合计分子分母再计算比例。</li><li>观察窗口内的非完整月份单独标记，不参与完整月变化结论。未完整覆盖的季度不与完整季度比较。</li><li>海光CPU、海光DCU、鲲鹏CPU分别识别。芯片筛选只限定分子，保留固定来源全部新闻分母；没有明确型号或角色不推断。</li><li>媒体标题与采购正文的证据强度不同，三个指标不合成分数。固定来源样本不代表全国无偏样本。</li></ol></section><section className="card"><h2>技术主题边界</h2>{taxonomy.technologies.map(t=><div className="taxonomy-row" key={t.id}><div><h3>{t.name}</h3><small>{t.layer}</small></div><div><p>{t.context_required}</p><small>排除：{t.exclude.join('、')}</small></div></div>)}</section></div>;}
